/* NeuroPress inference on a GPU-resident chunk, end to end.
 *
 * The point of this example is the data path, not the numbers: the chunk is
 * generated by a kernel and NEVER leaves the device. Its three selection
 * features are computed on the GPU, the network reads them from device memory,
 * and the ranking runs there too. The only host transfers are the 32x8 result
 * matrix at the end and the three features -- read separately, and only so
 * this program can print them.
 *
 * That is the same shape as upstream's gpucompress_infer_gpu /
 * runNNFusedInferenceCtx (nn_gpu.cu): compute stats on a stream, enqueue
 * inference on that same stream, synchronize once at the end.
 *
 * Build:  cmake -DCLIO_CORE_ENABLE_CUDA=ON ... && make neuropress_gpu_inference
 * Run:    ./bin/neuropress_gpu_inference [chunk_mib] [error_bound]
 */

#include <cuda_runtime.h>

#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

#include "clio_ctp/compress/model/neuropress_nn_predictor.h"
#include "clio_ctp/compress/model/predictor.h"
#include "clio_ctp/compress/preprocess/data_stats_gpu.h"

namespace model = ctp::compress::model;

/* The eight algorithms the network was trained on, in NeuroPress's own action
 * order (algo index 0-7). The base ids are Clio's registry ids; the 17/16/15
 * run is deliberately non-monotonic because upstream's ALGORITHM_NAMES puts
 * deflate before gdeflate before zstd (neural_net/core/configs.py). Getting
 * this order wrong silently trains and queries the wrong output head, so the
 * program checks it against the library rather than trusting the table. */
struct Algo {
  int base_id;
  const char *name;
};
static const Algo kAlgos[8] = {
    {13, "lz4"},     {14, "snappy"},   {17, "deflate"},  {16, "gdeflate"},
    {15, "zstd"},    {18, "ans"},      {23, "cascaded"}, {24, "bitcomp"},
};

/* A synthetic scientific field: smooth large-scale structure plus fine noise.
 *
 * Not random bytes -- uniform noise has maximal entropy and near-zero spatial
 * correlation, so every codec looks equally bad and the ranking is
 * uninteresting. This has the property real simulation output has: locally
 * smooth, so the second-derivative feature is small and shuffle/delta-friendly
 * codecs have something to exploit. */
__global__ void GenerateFieldKernel(float *out, size_t n, unsigned seed) {
  const size_t stride = static_cast<size_t>(blockDim.x) * gridDim.x;
  for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < n; i += stride) {
    const float x = static_cast<float>(i % 1024) * 0.0061359f;
    const float y = static_cast<float>(i / 1024) * 0.0061359f;
    const float smooth = __sinf(x) * __cosf(y) + 0.5f * __sinf(2.7f * x + y);

    /* Deterministic per-element hash, so a rerun reproduces the chunk without
       carrying a curand state around. */
    unsigned h = static_cast<unsigned>(i) * 2654435761u + seed;
    h ^= h >> 15;
    h *= 2246822519u;
    h ^= h >> 13;
    const float noise = (static_cast<float>(h & 0xFFFFFFu) / 16777215.0f) - 0.5f;

    out[i] = smooth + 0.02f * noise;
  }
}

int main(int argc, char **argv) {
  const double chunk_mib = (argc > 1) ? atof(argv[1]) : 4.0;
  const double error_bound = (argc > 2) ? atof(argv[2]) : 1e-3;

  const size_t num_elements =
      static_cast<size_t>(chunk_mib * 1024.0 * 1024.0) / sizeof(float);
  const size_t chunk_bytes = num_elements * sizeof(float);

  printf("=== NeuroPress inference on a GPU-resident chunk ===\n\n");

  int device_count = 0;
  if (cudaGetDeviceCount(&device_count) != cudaSuccess || device_count == 0) {
    printf("No CUDA device available.\n");
    return 77; /* skip, not fail */
  }

  /* ---- 1. Generate the chunk ON THE DEVICE ------------------------------ */
  float *d_data = nullptr;
  if (cudaMalloc(&d_data, chunk_bytes) != cudaSuccess) {
    printf("cudaMalloc failed for %zu bytes\n", chunk_bytes);
    return 1;
  }
  GenerateFieldKernel<<<256, 256>>>(d_data, num_elements, 12345u);
  if (cudaDeviceSynchronize() != cudaSuccess) {
    printf("generation kernel failed: %s\n",
           cudaGetErrorString(cudaGetLastError()));
    cudaFree(d_data);
    return 1;
  }
  printf("chunk        : %.2f MiB (%zu float32), generated by a kernel\n",
         chunk_bytes / (1024.0 * 1024.0), num_elements);
  printf("error bound  : %g  (quantize candidates are live above 0)\n\n",
         error_bound);

  /* ---- 2. Load the model ------------------------------------------------ */
  model::NeuroPressNNPredictor predictor;
  const std::string weights_dir = CLIO_CTP_NEUROPRESS_WEIGHTS_DIR;
  if (!predictor.Load(weights_dir) || !predictor.IsReady()) {
    printf("Could not load NeuroPress weights from %s\n", weights_dir.c_str());
    cudaFree(d_data);
    return 1;
  }

  /* Confirm the action-order table above matches what the library computes.
     A mismatch here would query a different head than intended, and would not
     otherwise be visible in the output. */
  for (int i = 0; i < 8; ++i) {
    const int got = model::NeuroPressAlgoIdForBaseId(kAlgos[i].base_id);
    if (got != i) {
      printf("action order mismatch: base_id %d (%s) is algo %d, expected %d\n",
             kAlgos[i].base_id, kAlgos[i].name, got, i);
      cudaFree(d_data);
      return 1;
    }
  }

  /* ---- 3. Features, computed on the device and LEFT there --------------- */
  void *stream = ctp::DeviceStatsStream();
  const void *device_stats = ctp::ComputeDeviceStatsResident(
      d_data, num_elements, ctp::DataType::FLOAT32, stream);
  if (device_stats == nullptr) {
    printf("ComputeDeviceStatsResident failed\n");
    cudaFree(d_data);
    return 1;
  }

  /* ---- 4. Build the 32-candidate action space --------------------------- */
  /* Shuffle outer, quantize inner, algorithm innermost, so slot order equals
     action order: action = algo + 8*quantize + 16*shuffle (internal.hpp). */
  model::DataFeatures data;
  data.chunk_size_bytes = static_cast<double>(chunk_bytes);
  data.data_type_float = 1.0;
  /* entropy/mad/second_derivative deliberately left at 0: the device path
     reads inputs 5-7 from device_stats and ignores these fields. */

  std::vector<model::CompressionFeatures> batch;
  std::vector<model::CandidateConfig> configs;
  batch.reserve(32);
  configs.reserve(32);
  for (int shuffle = 0; shuffle <= 1; ++shuffle) {
    for (int quant = 0; quant <= 1; ++quant) {
      for (int a = 0; a < 8; ++a) {
        model::CandidateConfig c;
        c.base_id = kAlgos[a].base_id;
        c.preset_id = 2; /* BALANCED; upstream has no preset concept */
        c.quantize = (quant != 0);
        c.byte_shuffle = (shuffle != 0);
        c.error_bound = (quant != 0) ? error_bound : 0.0;
        c.library_name = kAlgos[a].name;
        configs.push_back(c);
        batch.push_back(model::MakeCompressionFeatures(data, c));
      }
    }
  }

  /* ---- 5. Inference + ranking, both on the GPU -------------------------- */
  model::RankingWeights weights;
  weights.use_cost_model = true; /* NeuroPress's own policy, not ratio-only */

  std::vector<int> order;
  std::vector<double> scores;
  model::NeuroPressNNPredictor::FullOutputs full;

  const std::vector<model::CompressionPrediction> preds =
      predictor.PredictBatchDeviceStats(device_stats, batch, stream, &weights,
                                        &order, /*min_psnr=*/0.0, &scores,
                                        &full);
  if (preds.empty()) {
    printf("PredictBatchDeviceStats returned no predictions\n");
    cudaFree(d_data);
    return 1;
  }

  /* Read the three features out only now -- after inference was enqueued, so
     this readback never sat in the model's way. */
  double entropy = 0, mad = 0, deriv = 0;
  ctp::ReadDeviceFeatureStats(device_stats, &entropy, &mad, &deriv, stream);

  printf("device-resident features (NN inputs 5-7, never staged through host):\n");
  printf("  entropy           = %.6f\n", entropy);
  printf("  mad               = %.6f\n", mad);
  printf("  second derivative = %.6f\n\n", deriv);

  /* ---- 6. Print every candidate ----------------------------------------- */
  /* Two different orderings meet here, and mixing them silently produces a
     plausible-looking table with every cost attached to the wrong codec:
       - preds / FullOutputs are in SLOT order (slot i is configs[i]);
       - order / scores are in RANK order (position r is the r-th best),
         because the kernel writes out_order[tid]/out_scores[tid] after the
         bitonic sort has moved things (neuropress_nn_gpu_kernels.cu).
     Invert once, here, rather than indexing scores by slot anywhere below. */
  std::vector<double> cost_by_slot(preds.size(), 0.0);
  std::vector<int> rank_by_slot(preds.size(), -1);
  for (size_t r = 0; r < order.size(); ++r) {
    const int slot = order[r];
    cost_by_slot[slot] = -scores[r]; /* scores are -cost: higher is better */
    rank_by_slot[slot] = static_cast<int>(r);
  }

  printf("all 32 candidates, in action order (action = algo + 8*q + 16*sh):\n");
  printf("                          |------ ranking heads ------|"
         "-------- data-quality heads --------|\n");
  printf("act algo      q sh |  ratio   ct_ms   dt_ms  psnr_dB |"
         "     rmse   max_err      mae   ssim |     cost rank\n");
  printf("--------------------------------------------------------"
         "-------------------------------------------------\n");
  for (size_t i = 0; i < preds.size(); ++i) {
    const model::CandidateConfig &c = configs[i];
    const int action = model::NeuroPressActionId(c.base_id, c.quantize,
                                                 c.byte_shuffle);
    printf("%3d %-9s %d  %d |%7.2f %7.2f %7.2f %8.2f |%9.3g %9.3g %8.3g %6.3f "
           "|%9.4f %4d\n",
           action, c.library_name.c_str(), c.quantize ? 1 : 0,
           c.byte_shuffle ? 1 : 0, preds[i].compression_ratio,
           preds[i].compression_time_ms, preds[i].decompression_time_ms,
           preds[i].psnr_db, full.rmse[i], full.max_error[i], full.mae[i],
           full.ssim[i], cost_by_slot[i], rank_by_slot[i] + 1);
  }

  /* ---- 7. The decision -------------------------------------------------- */
  const int best_slot = order.empty() ? 0 : order[0];
  const model::CandidateConfig &w = configs[best_slot];
  printf("\nselected: action %d -- %s, quantize=%s, shuffle=%s\n",
         model::NeuroPressActionId(w.base_id, w.quantize, w.byte_shuffle),
         w.library_name.c_str(), w.quantize ? "yes" : "no",
         w.byte_shuffle ? "yes" : "no");
  printf("          predicted ratio %.2fx, compress %.2f ms, "
         "decompress %.2f ms, cost %.4f\n",
         preds[best_slot].compression_ratio,
         preds[best_slot].compression_time_ms,
         preds[best_slot].decompression_time_ms, cost_by_slot[best_slot]);

  printf("\ntop 5 by cost (lower is better):\n");
  for (size_t r = 0; r < order.size() && r < 5; ++r) {
    const int slot = order[r];
    const model::CandidateConfig &c = configs[slot];
    printf("  %zu. action %2d  %-9s q=%d sh=%d  cost %.4f  ratio %.2fx\n",
           r + 1,
           model::NeuroPressActionId(c.base_id, c.quantize, c.byte_shuffle),
           c.library_name.c_str(), c.quantize ? 1 : 0, c.byte_shuffle ? 1 : 0,
           cost_by_slot[slot], preds[slot].compression_ratio);
  }

  cudaFree(d_data);
  return 0;
}
