networking:
  port: 55947
runtime:
  num_threads: 4
  queue_depth: 1024
compose:
  - mod_name: clio_bdev
    pool_name: "/tmp/nyx-20gb-insitu/insitu20/chi_bdev.dat"
    pool_query: local
    pool_id: "301.0"
    bdev_type: file
    path: "/tmp/nyx-20gb-insitu/insitu20/chi_bdev.dat"
    capacity: "39424MB"
  - mod_name: clio_cte_compressor
    pool_name: cte_compressor
    pool_query: local
    pool_id: "512.0"
    next_pool_id: "513.0"
    neuropress_model_path: "/home/cc/clio-core/context-transport-primitives/src/compress/model/weights"
    neuropress_online_learning_enabled: true
    neuropress_exploration_enabled: true
    neuropress_exploration_k: 3
    neuropress_exploration_threshold: 0
    neuropress_best_mode: false


  - mod_name: clio_cte_core
    pool_name: cte_core
    pool_query: local
    pool_id: "513.0"
    storage:
      - path: "/tmp/nyx-20gb-insitu/insitu20/cte_tier.dat"
        bdev_type: "file"
        capacity_limit: "19712MB"
        score: 1.0
        persistence_level: "temporary"
    performance:
      metadata_log_path: "/tmp/nyx-20gb-insitu/insitu20/cte_metadata_log"
      transaction_log_capacity: "32MB"
    dpe:
      dpe_type: "max_bw"
