/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 * This file is part of IOWarp Core.
 * BSD 3-Clause License. See LICENSE file.
 */

/**
 * @file neuropress_gpu_chunk_equivalence.cc
 * @brief Runs native NeuroPress and Clio-NeuroPress over the SAME GPU-resident
 *        chunk and compares them callback by callback.
 *
 * WHAT THIS ANSWERS. Not "does the final compressed output match" -- that
 * question has been asked before and its answer is uninformative when it is
 * "no", because it does not say WHERE. This walks the pipeline stage by stage
 * from a chunk that is already in GPU memory and reports the FIRST callback at
 * which the two implementations stop agreeing, with the device pointers, the
 * hashes and a byte-level comparison at each step.
 *
 * THE INPUT IS GPU-RESIDENT FROM BIRTH. Each chunk is generated by a CUDA
 * kernel into a cudaMalloc'd buffer. There is no host original that was
 * uploaded; there is nothing to upload. The pointer is then classified through
 * cudaPointerGetAttributes and the run refuses to continue unless the driver
 * itself says DEVICE.
 *
 * BOTH SIDES SEE THE SAME BYTES. One buffer is generated and both
 * implementations read it. The harness additionally byte-compares the two
 * sides' views of the input, so "the inputs were equal" is measured rather
 * than assumed.
 *
 * Run:
 *   bin/neuropress_gpu_chunk_equivalence [--out DIR] [--no-e2e]
 *
 * Environment:
 *   NPEQ_OUT_DIR   where the trace and report files are written
 *   NPEQ_E2E       0 to skip the end-to-end production cross-check
 */

#include <cuda_runtime.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <string>
#include <vector>

#include "callback_trace.h"
#include "clio_path.h"
#include "comparison.h"
#include "device_probe.h"
#include "native_path.h"

// The end-to-end cross-check drives Clio's real chimod path, so it needs the
// runtime client headers. Everything above this line is independent of them.
#include <clio_runtime/clio_runtime.h>
#include <clio_runtime/bdev/bdev_client.h>
#include <clio_cte/core/core_client.h>
#include <clio_cte/compressor/compressor_client.h>
#include <clio_ctp/compress/compress_factory.h>

namespace {

using npeq::ChunkRegime;

/** One chunk of the multi-chunk matrix. */
struct ChunkPlan {
  ChunkRegime regime;
  size_t bytes;
  double error_bound;
  const char *why;
};

/**
 * The matrix.
 *
 * Chosen to reach the corners the harness has to cover: shuffle selected and
 * not, quantization selected and not, more than one algorithm, a chunk sitting
 * near the error-bound boundary, a small chunk and a large one. Which action
 * each regime ACTUALLY produces is not predicted here -- it is measured, and
 * the report prints it. The `why` string records the intent so a regime that
 * stops covering its corner is visible rather than silently redundant.
 */
const ChunkPlan kPlan[] = {
    {ChunkRegime::kConstant, 4u << 20, 0.0,
     "maximally compressible, lossless: expect a cheap codec"},
    {ChunkRegime::kSmoothWave, 4u << 20, 0.0,
     "low entropy, lossless: the shuffle dimension should matter here"},
    {ChunkRegime::kHighEntropy, 4u << 20, 0.0,
     "incompressible, lossless: a different corner of the action space"},
    {ChunkRegime::kSmoothWave, 4u << 20, 1e-3,
     "same data, positive bound: quantize actions become rankable"},
    {ChunkRegime::kNoisyWave, 4u << 20, 1e-2,
     "loose bound: quantization should be attractive"},
    {ChunkRegime::kSmallMagnitude, 4u << 20, 1e-6,
     "values ~1e-6 against a 1e-6 bound: the error-bound boundary"},
    {ChunkRegime::kStepped, 256u << 10, 0.0, "small chunk"},
    {ChunkRegime::kMixed, 32u << 20, 1e-3, "large chunk, mixed regimes"},
};

std::string EnvOr(const char *name, const std::string &fallback) {
  const char *v = std::getenv(name);
  return (v != nullptr && v[0] != '\0') ? std::string(v) : fallback;
}

#define CUDA_OK(expr)                                                        \
  do {                                                                       \
    cudaError_t rc_ = (expr);                                                \
    if (rc_ != cudaSuccess) {                                                \
      std::cerr << "CUDA error at " << __LINE__ << ": "                      \
                << cudaGetErrorString(rc_) << std::endl;                     \
      return 1;                                                              \
    }                                                                        \
  } while (0)

/**
 * The end-to-end production cross-check.
 *
 * The stage decomposition above calls the same functions Clio's compressor
 * runtime calls, but it calls them itself. This runs the WHOLE chimod path --
 * AsyncDynamicSchedule, exactly as the sibling neuropress_gpu_direct example
 * does -- and reports the selection it produced, so the decomposition can be
 * checked against the thing it claims to decompose. If they disagree, the
 * decomposition is not a faithful model of production and the whole trace is
 * suspect; that is worth knowing and is why this exists.
 */
struct E2ESelection {
  bool present = false;
  std::string lib_name;
  int algo_idx = -1;
  bool quantize = false;
  bool shuffle = false;
};

struct E2EResult {
  bool ran = false;
  std::string error;
  /** What the chimod SELECTED, from the runtime's own selection log. */
  std::vector<E2ESelection> selections;
  /**
   * What the chimod finally STORED. Note wire id 0 is overloaded: it is
   * brotli's registered id AND the sentinel the runtime writes when
   * compression turned out not to reduce the chunk
   * (compressor_runtime.cc:2685). It is therefore reported as "stored raw",
   * never resolved through NameForWireId -- doing that reads a not-beneficial
   * chunk as a brotli chunk, which is wrong in a way that looks entirely
   * plausible.
   */
  std::vector<int> applied_wire_ids;
};

/**
 * Read the runtime's per-chunk selection log.
 *
 * This is Clio's OWN record of what NeuroPress chose, written from
 * DynamicSchedule before the codec runs (compressor_runtime.cc:1498) -- so it
 * exists for every chunk, including those whose compressed output was later
 * discarded as not beneficial. That makes it the right thing to compare a
 * SELECTION trace against; the applied library is a storage decision taken
 * further downstream.
 */
void ParseSelectionLog(const std::string &path, E2EResult *out) {
  std::FILE *fp = std::fopen(path.c_str(), "r");
  if (fp == nullptr) return;
  char line[2048];
  bool header = true;
  while (std::fgets(line, sizeof(line), fp) != nullptr) {
    if (header) {
      header = false;
      continue;
    }
    std::vector<std::string> col;
    std::string cur;
    for (const char *p = line; *p != '\0'; ++p) {
      if (*p == ',') {
        col.push_back(cur);
        cur.clear();
      } else if (*p != '\n' && *p != '\r') {
        cur += *p;
      }
    }
    col.push_back(cur);
    // seq,blob,chunk_bytes,entropy,mad,second_deriv,wire_lib,lib_name,
    // algo_idx,quantize,shuffle,preset,...
    if (col.size() < 12) continue;
    const std::string &blob = col[1];
    const size_t pos = blob.rfind("npeq_chunk_");
    if (pos == std::string::npos) continue;
    const int idx = std::atoi(blob.c_str() + pos + std::strlen("npeq_chunk_"));
    if (idx < 0 || static_cast<size_t>(idx) >= out->selections.size()) continue;
    // The runtime logs each chunk once per selection; keep the FIRST, which is
    // the write-path decision.
    if (out->selections[idx].present) continue;
    out->selections[idx].present = true;
    out->selections[idx].lib_name = col[7];
    out->selections[idx].algo_idx = std::atoi(col[8].c_str());
    out->selections[idx].quantize = std::atoi(col[9].c_str()) != 0;
    out->selections[idx].shuffle = std::atoi(col[10].c_str()) != 0;
  }
  std::fclose(fp);
}

E2EResult RunProductionCrossCheck(const std::vector<ChunkPlan> &plan,
                                  const std::vector<void *> &chunks,
                                  const std::string &weights_dir,
                                  const std::string &selection_log) {
  E2EResult out;
  const std::string backend_file = "/tmp/npeq_chunk_equivalence_backend.dat";

  // Turn on the runtime's own selection log before the runtime starts: it
  // reads the variable once, into a function-local static.
  setenv("CLIO_NEUROPRESS_SELECTION_LOG", selection_log.c_str(), 1);

  if (!clio::run::CLIO_INIT(clio::run::RuntimeMode::kClient, true)) {
    out.error = "CLIO_INIT failed";
    return out;
  }
  if (!clio::cte::core::CLIO_CTE_CLIENT_INIT()) {
    out.error = "CLIO_CTE_CLIENT_INIT failed";
    return out;
  }
  auto *cte_client = CLIO_CTE_CLIENT;

  auto reg = cte_client->AsyncRegisterTarget(
      backend_file, clio::run::bdev::BdevType::kFile,
      static_cast<clio::run::u64>(1) << 30, clio::run::PoolQuery::Local(),
      clio::run::PoolId(940, 0));
  reg.Wait();
  if (reg->GetReturnCode() != 0) {
    out.error = "RegisterTarget failed";
    return out;
  }

  clio::run::PoolId compressor_pool_id(941, 1);
  clio::cte::compressor::CompressorConfig cfg;
  cfg.neuropress_model_path_ = weights_dir;
  clio::cte::compressor::Client compressor;
  auto create = compressor.AsyncCreateCompressor(
      clio::run::PoolQuery::Local(), "npeq_equivalence_pool",
      compressor_pool_id, cfg);
  create.Wait();
  if (create->GetReturnCode() != 0) {
    out.error = "CreateCompressor failed";
    return out;
  }
  compressor.Init(compressor_pool_id);

  auto tag = cte_client->AsyncGetOrCreateTag("npeq_chunk_equivalence");
  tag.Wait();
  if (tag->GetReturnCode() != 0) {
    out.error = "GetOrCreateTag failed";
    return out;
  }
  const auto tag_id = tag->tag_id_;

  out.applied_wire_ids.assign(plan.size(), -1);
  out.selections.assign(plan.size(), E2ESelection{});

  for (size_t i = 0; i < plan.size(); ++i) {
    clio::cte::core::Context ctx;
    ctx.data_type_ = 1;  // float32, as the traced path declares
    ctx.error_bound_ = plan[i].error_bound;

    // Register this chunk's device memory so the ShmPtr the compressor
    // receives resolves to a REAL device pointer through CUDA IPC, rather than
    // being staged to the host. Without this the chimod would see host memory
    // and take a different path entirely -- which is D20-1, and not what this
    // cross-check is about.
    char *registered = nullptr;
    ctp::ipc::AllocatorId alloc_id = CLIO_IPC->AllocateAndRegisterGpuBackend(
        /*gpu_id=*/0, clio::run::gpu::IpcManager::MemKind::kDeviceMem,
        plan[i].bytes, &registered);
    if (alloc_id.IsNull()) {
      out.error = "AllocateAndRegisterGpuBackend failed";
      return out;
    }
    if (cudaMemcpy(registered, chunks[i], plan[i].bytes,
                   cudaMemcpyDeviceToDevice) != cudaSuccess) {
      out.error = "staging the chunk into the registered backend failed";
      CLIO_IPC->FreeGpuBackend(0, alloc_id);
      return out;
    }

    ctp::ipc::ShmPtr<> blob_data;
    blob_data.alloc_id_ = alloc_id;
    blob_data.off_ = reinterpret_cast<clio::run::u64>(registered);

    auto fut = compressor.AsyncDynamicSchedule(
        clio::run::PoolQuery::Local(), tag_id,
        "npeq_chunk_" + std::to_string(i), /*offset=*/0, plan[i].bytes,
        blob_data, -1.0f, ctx, 0, cte_client->pool_id_);
    fut.Wait();
    if (fut->GetReturnCode() == 0) {
      out.applied_wire_ids[i] = fut->context_.compress_lib_;
    }
    CLIO_IPC->FreeGpuBackend(0, alloc_id);
  }

  ParseSelectionLog(selection_log, &out);
  out.ran = true;
  return out;
}

}  // namespace

int main(int argc, char **argv) {
  std::string out_dir = EnvOr("NPEQ_OUT_DIR", ".");
  bool run_e2e = EnvOr("NPEQ_E2E", "1") != "0";
  bool repeat_self_check = EnvOr("NPEQ_SELF_CHECK", "1") != "0";
  /**
   * Override every chunk's error bound with one value.
   *
   * Negative means "use the per-chunk bound from the plan". Overriding is not
   * the same experiment as the default matrix: the plan deliberately mixes
   * lossless and lossy chunks so both halves of the action space are covered,
   * whereas a single bound applied everywhere makes quantize actions rankable
   * on every chunk and drops lossless coverage entirely. Both are worth
   * running; the report records which one this was.
   */
  double error_bound_override =
      std::atof(EnvOr("NPEQ_ERROR_BOUND", "-1").c_str());
  /**
   * Size each chunk's ABSOLUTE bound as a fraction of that chunk's own range.
   *
   * A single absolute bound cannot exercise quantization across this matrix:
   * the regimes span data ranges from ~2e2 to ~2e6, and the precision the
   * quantizer picks follows `num_bins = (range / (2*eb)) * 1.1` -- so one
   * bound that puts a narrow chunk in 8-bit puts a wide one in 32-bit, where
   * float32 -> int32 saves nothing and the cost model correctly declines to
   * quantize at all. Scaling by the range makes `num_bins ~ 1.1 / (2*R)`,
   * i.e. the same precision on every chunk regardless of its magnitude:
   *   R = 0.005 -> ~110 bins  -> 8-bit
   *   R = 0.001 -> ~550 bins  -> 16-bit
   *
   * The bound handed to both implementations is still ABSOLUTE. Only the
   * choice of number is relative; its meaning is not (D16-1 was precisely a
   * relative/absolute mix-up, and this must not reintroduce one).
   */
  double error_bound_rel =
      std::atof(EnvOr("NPEQ_ERROR_BOUND_REL", "-1").c_str());
  for (int i = 1; i < argc; ++i) {
    const std::string arg = argv[i];
    if (arg == "--out" && i + 1 < argc) {
      out_dir = argv[++i];
    } else if (arg == "--error-bound" && i + 1 < argc) {
      error_bound_override = std::atof(argv[++i]);
    } else if (arg == "--error-bound-rel" && i + 1 < argc) {
      error_bound_rel = std::atof(argv[++i]);
    } else if (arg == "--no-e2e") {
      run_e2e = false;
    } else if (arg == "--no-self-check") {
      repeat_self_check = false;
    } else if (arg == "--help") {
      std::cout << "usage: " << argv[0]
                << " [--out DIR] [--error-bound EB] [--no-e2e] "
                   "[--no-self-check]\n";
      return 0;
    }
  }

  int devices = 0;
  if (cudaGetDeviceCount(&devices) != cudaSuccess || devices == 0) {
    std::cerr << "No CUDA device available; this harness compares two GPU "
                 "pipelines and cannot run without one." << std::endl;
    return 77;  // ctest SKIP_RETURN_CODE
  }

  const std::string weights_dir = CLIO_CTP_NEUROPRESS_WEIGHTS_DIR;
  std::string weights_file = weights_dir;
  if (!weights_file.empty() && weights_file.back() != '/') weights_file += '/';
  weights_file += "model.nnwt";

  auto &recorder = npeq::Recorder::Instance();
  const bool cupti_ok = recorder.StartInstrumentation();
  if (!cupti_ok) {
    std::cerr << "WARNING: CUPTI could not be started ("
              << recorder.InstrumentationError()
              << "). Transfer and kernel records will be empty; every other "
                 "check still runs." << std::endl;
  }

  std::string err;
  if (!npeq::NativeInit(weights_file, &err)) {
    std::cerr << "native NeuroPress init failed: " << err << std::endl;
    return 1;
  }
  if (!npeq::ClioInitPredictor(weights_dir, &err)) {
    std::cerr << "Clio NeuroPress predictor init failed: " << err << std::endl;
    return 1;
  }

  std::vector<ChunkPlan> plan(std::begin(kPlan), std::end(kPlan));
  if (error_bound_override >= 0.0) {
    for (auto &p : plan) p.error_bound = error_bound_override;
  }
  std::vector<void *> chunks(plan.size(), nullptr);

  std::vector<npeq::ChunkTrace> native_traces;
  std::vector<npeq::ChunkTrace> clio_traces;
  std::vector<npeq::ChunkComparison> comparisons;

  std::cout << "NeuroPress <-> Clio callback-trace equivalence\n"
            << "  weights:      " << weights_file << "\n"
            << "  chunks:       " << plan.size() << "\n"
            << "  error bound:  "
            << (error_bound_rel > 0.0
                    ? ("ABSOLUTE, sized per chunk at " +
                       std::to_string(error_bound_rel) + " x that chunk's range")
                    : error_bound_override >= 0.0
                          ? ("OVERRIDDEN to " +
                             std::to_string(error_bound_override) +
                             " on every chunk")
                          : std::string("per-chunk, from the plan"))
            << "\n"
            << "  instrumented: " << (cupti_ok ? "CUPTI runtime-API callbacks"
                                               : "NO (CUPTI unavailable)")
            << "\n\n";

  for (size_t i = 0; i < plan.size(); ++i) {
    const auto &p = plan[i];
    const size_t num_elements = p.bytes / sizeof(float);

    // ---- the chunk is born on the device ----
    float *d_chunk = nullptr;
    CUDA_OK(cudaMalloc(&d_chunk, p.bytes));
    chunks[i] = d_chunk;
    if (!npeq::FillChunk(d_chunk, num_elements, p.regime,
                         static_cast<uint32_t>(i + 1))) {
      std::cerr << "chunk " << i << ": generation failed" << std::endl;
      return 1;
    }
    const bool device_verified =
        npeq::ClassifyPointer(d_chunk) == npeq::PointerKind::kDevice;
    if (!device_verified) {
      std::cerr << "chunk " << i
                << ": the driver does not report the input as DEVICE memory; "
                   "refusing to compare a path that is not the one under test"
                << std::endl;
      return 1;
    }
    uint64_t input_hash = 0;
    npeq::HashAsHarness(d_chunk, p.bytes, &input_hash);

    // Size this chunk's ABSOLUTE bound from its own range, if asked. Done
    // after generation because it needs the data, and before either side runs
    // because both must receive the identical number.
    if (error_bound_rel > 0.0) {
      double lo = 0.0, hi = 0.0;
      if (npeq::ComputeDeviceRange(d_chunk, num_elements, &lo, &hi)) {
        const double range = hi - lo;
        // Constant data has zero range; upstream clamps it to 1.0 internally
        // (quantization_kernels.cu), so scale against that rather than
        // producing a zero bound, which would switch quantization off on the
        // one chunk that exercises the clamp.
        plan[i].error_bound =
            error_bound_rel * (range > 0.0 ? range : 1.0);
        std::cout << "  range [" << lo << ", " << hi << "] -> absolute eb "
                  << plan[i].error_bound << std::endl;
      }
    }
    // `p` is a reference into `plan`, so it already reflects the update above.

    std::cout << "chunk " << i << "  " << npeq::ChunkRegimeName(p.regime)
              << "  " << (p.bytes >> 10) << " KiB  eb=" << p.error_bound
              << "  -- " << p.why << std::endl;

    // ---- native ----
    recorder.BeginChunk(static_cast<int>(i), npeq::Side::kNative,
                        npeq::ChunkRegimeName(p.regime), p.bytes,
                        p.error_bound);
    npeq::NativeChunkResult nat =
        npeq::NativeRunChunk(d_chunk, p.bytes, p.error_bound,
                             static_cast<int>(i));
    npeq::ChunkTrace nat_trace = recorder.EndChunk();
    nat_trace.input_device_verified = device_verified;
    nat_trace.input_hash = input_hash;
    if (!nat.ok) {
      std::cerr << "  native failed: " << nat.error << std::endl;
      return 1;
    }

    // ---- clio ----
    recorder.BeginChunk(static_cast<int>(i), npeq::Side::kClio,
                        npeq::ChunkRegimeName(p.regime), p.bytes,
                        p.error_bound);
    npeq::ClioChunkResult cli =
        npeq::ClioRunChunk(d_chunk, p.bytes, p.error_bound,
                           static_cast<int>(i));
    npeq::ChunkTrace cli_trace = recorder.EndChunk();
    cli_trace.input_device_verified = device_verified;
    cli_trace.input_hash = input_hash;
    if (!cli.ok) {
      std::cerr << "  clio failed: " << cli.error << std::endl;
      return 1;
    }

    std::cout << "    native action=" << nat.action << " ("
              << (nat.shuffle_selected ? "shuffle " : "")
              << (nat.quantize_selected ? "quant " : "") << "algo "
              << nat.algo << ")   clio action=" << cli.action << " ("
              << (cli.shuffle_selected ? "shuffle " : "")
              << (cli.quantize_selected ? "quant " : "") << "algo "
              << cli.algo << ")" << std::endl;

    // ---- each side against a second run of itself ----
    //
    // Runs the whole pipeline again on the same chunk and keeps only the
    // payload. Without this the cross-side byte comparison below cannot be
    // interpreted: a codec whose output depends on manager reuse history would
    // look like a divergence. The repeat traces are discarded -- only the bytes
    // matter here.
    npeq::NativeChunkResult nat_repeat;
    npeq::ClioChunkResult cli_repeat;
    if (repeat_self_check) {
      recorder.BeginChunk(static_cast<int>(i), npeq::Side::kNative,
                          npeq::ChunkRegimeName(p.regime), p.bytes,
                          p.error_bound);
      nat_repeat = npeq::NativeRunChunk(d_chunk, p.bytes, p.error_bound,
                                        static_cast<int>(i));
      recorder.EndChunk();

      recorder.BeginChunk(static_cast<int>(i), npeq::Side::kClio,
                          npeq::ChunkRegimeName(p.regime), p.bytes,
                          p.error_bound);
      cli_repeat = npeq::ClioRunChunk(d_chunk, p.bytes, p.error_bound,
                                      static_cast<int>(i));
      recorder.EndChunk();
    }

    npeq::SideArtifacts nat_art;
    nat_art.input = d_chunk;
    nat_art.input_bytes = p.bytes;
    nat_art.quantized = nat.quantized_device;
    nat_art.quantized_bytes = nat.quantized_bytes;
    nat_art.shuffled = nat.shuffled_device;
    nat_art.shuffled_bytes = nat.shuffled_bytes;
    nat_art.dequantized = nat.dequantized_device;
    nat_art.dequantized_bytes = nat.dequantized_bytes;
    nat_art.bound_checked = nat.bound_checked;
    nat_art.bound_violations = nat.bound_violations;
    nat_art.requested_error_bound = p.error_bound;
    nat_art.payload = nat.payload_device;
    nat_art.payload_bytes = nat.payload_bytes;
    nat_art.payload_repeat = nat_repeat.payload_device;
    nat_art.payload_repeat_bytes = nat_repeat.payload_bytes;

    npeq::SideArtifacts cli_art;
    cli_art.input = d_chunk;
    cli_art.input_bytes = p.bytes;
    cli_art.quantized = cli.quantized_device;
    cli_art.quantized_bytes = cli.quantized_bytes;
    cli_art.shuffled = cli.shuffled_device;
    cli_art.shuffled_bytes = cli.shuffled_bytes;
    cli_art.dequantized = cli.dequantized_device;
    cli_art.dequantized_bytes = cli.dequantized_bytes;
    cli_art.bound_checked = cli.bound_checked;
    cli_art.bound_violations = cli.bound_violations;
    cli_art.requested_error_bound = p.error_bound;
    cli_art.payload = cli.payload_device;
    cli_art.payload_bytes = cli.payload_bytes;
    cli_art.payload_repeat = cli_repeat.payload_device;
    cli_art.payload_repeat_bytes = cli_repeat.payload_bytes;

    comparisons.push_back(
        npeq::CompareChunk(nat_trace, cli_trace, nat_art, cli_art));
    std::cout << "    -> " << (comparisons.back().pass ? "PASS" : "FAIL");
    if (!comparisons.back().pass) {
      std::cout << "   first divergence: " << comparisons.back().first_divergence;
    }
    std::cout << "\n" << std::endl;

    native_traces.push_back(std::move(nat_trace));
    clio_traces.push_back(std::move(cli_trace));

    npeq::NativeReleaseChunk(&nat);
    npeq::ClioReleaseChunk(&cli);
    npeq::NativeReleaseChunk(&nat_repeat);
    npeq::ClioReleaseChunk(&cli_repeat);
  }

  // ---- end-to-end production cross-check ----
  std::string preamble;
  {
    std::string e2e_note;
    if (run_e2e) {
      E2EResult e2e = RunProductionCrossCheck(plan, chunks, weights_dir,
                                              out_dir + "/e2e_selection.csv");
      if (!e2e.ran) {
        e2e_note =
            "End-to-end production cross-check: DID NOT RUN (" + e2e.error +
            "). The stage decomposition below therefore stands on its own; it "
            "calls the same functions compressor_runtime.cc calls, but that "
            "was not confirmed against a full AsyncDynamicSchedule in this "
            "run.\n";
      } else {
        int agree = 0, compared = 0;
        std::string detail;
        std::string storage;
        for (size_t i = 0; i < plan.size(); ++i) {
          const npeq::TraceEntry *sel =
              clio_traces[i].Find(npeq::Stage::kSelection);
          if (e2e.selections[i].present && sel != nullptr) {
            ++compared;
            const auto &e = e2e.selections[i];
            const bool same = e.algo_idx == sel->selection.algo &&
                              e.quantize == sel->selection.quantize &&
                              e.shuffle == sel->selection.shuffle;
            if (same) {
              ++agree;
            } else {
              detail += "      chunk " + std::to_string(i) +
                        ": end-to-end selected " + e.lib_name + " (algo " +
                        std::to_string(e.algo_idx) +
                        " quant=" + (e.quantize ? "1" : "0") +
                        " shuffle=" + (e.shuffle ? "1" : "0") +
                        "), the traced decomposition selected " +
                        sel->selection.algo_name + " (algo " +
                        std::to_string(sel->selection.algo) +
                        " quant=" + (sel->selection.quantize ? "1" : "0") +
                        " shuffle=" + (sel->selection.shuffle ? "1" : "0") +
                        ")\n";
            }
          }
          // The storage outcome is a separate decision and is reported as one.
          if (e2e.applied_wire_ids[i] == 0) {
            storage += "      chunk " + std::to_string(i) +
                       ": stored RAW -- the codec ran but did not reduce the "
                       "chunk, so the runtime discarded its output "
                       "(compressor_runtime.cc:2685). This is a Clio storage "
                       "policy downstream of selection, not a selection "
                       "difference\n";
          }
        }
        e2e_note = "End-to-end production cross-check (AsyncDynamicSchedule "
                   "through the real chimod, selection read from Clio's own "
                   "per-chunk selection log): " +
                   std::to_string(agree) + " / " + std::to_string(compared) +
                   " chunks selected the same action as the traced stage "
                   "decomposition.\n";
        if (!detail.empty()) {
          e2e_note +=
              "    The decomposition does NOT faithfully model production for:\n" +
              detail;
        }
        if (!storage.empty()) {
          e2e_note += "    Storage outcomes worth recording:\n" + storage;
        }
      }
    } else {
      e2e_note = "End-to-end production cross-check: skipped (--no-e2e).\n";
    }

    preamble =
        "Native NeuroPress is the ground truth. Both sides read the SAME "
        "device buffer.\n"
        "\n"
        "Error bound: " +
        (error_bound_override >= 0.0
             ? ("OVERRIDDEN to " + std::to_string(error_bound_override) +
                " on every chunk (--error-bound). Quantize actions are "
                "rankable everywhere; this run carries NO lossless coverage.")
             : std::string("per-chunk, from the plan (mixed lossless and "
                           "lossy).")) +
        "\n\n"
        "Instrumentation: " +
        std::string(cupti_ok
                        ? "CUPTI runtime-API callbacks. Every cudaMemcpy, "
                          "cudaMemcpyAsync and kernel launch below was "
                          "observed, not inferred."
                        : "NONE -- CUPTI unavailable; transfer and kernel "
                          "columns are empty.") +
        "\n"
        "Native has no callback API; its stage entry points and its own "
        "per-chunk\n"
        "diagnostics record (gpucompress_chunk_diag_t) are used as the "
        "callback\n"
        "boundaries. Nothing here reimplements a NeuroPress algorithm.\n"
        "\n" +
        e2e_note +
        "\n"
        "Test-harness transfers (hashing and byte comparison) are tagged "
        "TEST_HARNESS_TRANSFER\n"
        "and are excluded from every production transfer count.\n";
  }

  // ---- outputs ----
  const std::string native_json = out_dir + "/native_trace.json";
  const std::string clio_json = out_dir + "/clio_trace.json";
  const std::string cmp_json = out_dir + "/callback_comparison.json";
  const std::string report_txt = out_dir + "/callback_trace_report.txt";

  bool wrote = npeq::WriteTraceJson(native_json, native_traces);
  wrote = npeq::WriteTraceJson(clio_json, clio_traces) && wrote;
  wrote = npeq::WriteComparisonJson(cmp_json, comparisons) && wrote;
  wrote = npeq::WriteReport(report_txt, native_traces, clio_traces, comparisons,
                            preamble) &&
          wrote;

  npeq::PrintReport(std::cout, native_traces, clio_traces, comparisons,
                    preamble);

  if (wrote) {
    std::cout << "\nWrote:\n  " << native_json << "\n  " << clio_json << "\n  "
              << cmp_json << "\n  " << report_txt << std::endl;
  } else {
    std::cerr << "\nWARNING: one or more output files could not be written to "
              << out_dir << std::endl;
  }

  for (void *c : chunks) {
    if (c != nullptr) cudaFree(c);
  }
  npeq::ClioShutdownPredictor();
  npeq::NativeShutdown();
  recorder.StopInstrumentation();

  int failed = 0;
  for (const auto &c : comparisons) {
    if (!c.pass) ++failed;
  }
  return failed == 0 ? 0 : 2;
}
