/* The upstream-side twin of example/neuropress_gpu_inference.cu.
 *
 * Same chunk, same generation kernel, same 32 actions, same table -- but every
 * number here comes from NeuroPress's own code: its stats pipeline
 * (runStatsOnlyPipeline -> stats_kernel.cu / entropy_kernel.cu) and its own
 * fused inference (runNNFusedInferenceCtx -> nn_gpu.cu). Nothing Clio computes
 * is read, and nothing is laundered between the two.
 *
 * Run this and the Clio example side by side to compare: the generation kernel
 * is copied verbatim rather than shared, so the two programs cannot drift into
 * agreeing because they accidentally use one implementation.
 *
 * Not registered with ctest -- it asserts nothing, it prints.
 */

#include <cuda_runtime.h>

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <numeric>
#include <string>
#include <vector>

#include "api/internal.hpp"
#include "nn/nn_weights.h"
#include "stats/auto_stats_gpu.h"

namespace gpucompress {
/* Upstream's byte->statistics pipeline, declared the way the parity harnesses
   in this directory declare it. */
int runStatsOnlyPipeline(const void *d_input, size_t input_size,
                         cudaStream_t stream, double *out_entropy,
                         double *out_mad, double *out_deriv);
void freeStatsWorkspace();
}  // namespace gpucompress

namespace {

/* Upstream's action order is its own: action % 8 indexes ALGORITHM_NAMES
   (neural_net/core/configs.py), which is what these labels are. */
const char *kAlgoName[8] = {"lz4",  "snappy", "deflate",  "gdeflate",
                            "zstd", "ans",    "cascaded", "bitcomp"};

/* Byte-for-byte the same field the Clio example generates. Any edit here must
   be mirrored there or the two tables stop being comparable. */
__global__ void GenerateFieldKernel(float *out, size_t n, unsigned seed) {
  const size_t stride = static_cast<size_t>(blockDim.x) * gridDim.x;
  for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < n; i += stride) {
    const float x = static_cast<float>(i % 1024) * 0.0061359f;
    const float y = static_cast<float>(i / 1024) * 0.0061359f;
    const float smooth = __sinf(x) * __cosf(y) + 0.5f * __sinf(2.7f * x + y);

    unsigned h = static_cast<unsigned>(i) * 2654435761u + seed;
    h ^= h >> 15;
    h *= 2246822519u;
    h ^= h >> 13;
    const float noise = (static_cast<float>(h & 0xFFFFFFu) / 16777215.0f) - 0.5f;

    out[i] = smooth + 0.02f * noise;
  }
}

}  // namespace

int main(int argc, char **argv) {
  const double chunk_mib = (argc > 1) ? atof(argv[1]) : 4.0;
  const double error_bound = (argc > 2) ? atof(argv[2]) : 1e-3;

  const size_t num_elements =
      static_cast<size_t>(chunk_mib * 1024.0 * 1024.0) / sizeof(float);
  const size_t chunk_bytes = num_elements * sizeof(float);

  printf("=== UPSTREAM NeuroPress inference on a GPU-resident chunk ===\n\n");

  int device_count = 0;
  if (cudaGetDeviceCount(&device_count) != cudaSuccess || device_count == 0) {
    printf("No CUDA device available.\n");
    return 77;
  }

  /* ---- 1. Generate the chunk ON THE DEVICE ------------------------------ */
  float *d_data = nullptr;
  if (cudaMalloc(&d_data, chunk_bytes) != cudaSuccess) {
    printf("cudaMalloc failed for %zu bytes\n", chunk_bytes);
    return 1;
  }
  GenerateFieldKernel<<<256, 256>>>(d_data, num_elements, 12345u);
  if (cudaDeviceSynchronize() != cudaSuccess) {
    printf("generation kernel failed: %s\n",
           cudaGetErrorString(cudaGetLastError()));
    cudaFree(d_data);
    return 1;
  }
  printf("chunk        : %.2f MiB (%zu float32), generated by a kernel\n",
         chunk_bytes / (1024.0 * 1024.0), num_elements);
  printf("error bound  : %g  (quantize candidates are live above 0)\n\n",
         error_bound);

  /* ---- 2. Load upstream's weights --------------------------------------- */
  const std::string nnwt =
      std::string(CLIO_CTP_NEUROPRESS_WEIGHTS_DIR) + "/model.nnwt";
  if (!gpucompress::loadNNFromBinary(nnwt.c_str())) {
    printf("Could not load NeuroPress weights from %s\n", nnwt.c_str());
    cudaFree(d_data);
    return 1;
  }

  cudaStream_t stream = nullptr;
  if (cudaStreamCreate(&stream) != cudaSuccess) {
    cudaFree(d_data);
    return 1;
  }

  /* ---- 3. Upstream's own statistics, on the device ---------------------- */
  double entropy = 0, mad = 0, deriv = 0;
  if (gpucompress::runStatsOnlyPipeline(d_data, chunk_bytes, stream, &entropy,
                                        &mad, &deriv) != 0) {
    printf("runStatsOnlyPipeline failed\n");
    cudaFree(d_data);
    return 1;
  }

  /* Upstream's inference reads an AutoStatsGPU from device memory. */
  AutoStatsGPU *d_stats = nullptr;
  if (cudaMalloc(&d_stats, sizeof(AutoStatsGPU)) != cudaSuccess) {
    cudaFree(d_data);
    return 1;
  }
  AutoStatsGPU h{};
  h.entropy = entropy;
  h.mad_normalized = mad;
  h.deriv_normalized = deriv;
  h.num_elements = num_elements;
  cudaMemcpy(d_stats, &h, sizeof(h), cudaMemcpyHostToDevice);

  printf("device-resident features (NN inputs 5-7):\n");
  printf("  entropy           = %.6f\n", entropy);
  printf("  mad               = %.6f\n", mad);
  printf("  second derivative = %.6f\n\n", deriv);

  /* ---- 4. Fused inference: all 32 configs, upstream's own kernel -------- */
  CompContext ctx{};
  ctx.stream = stream;
  if (cudaMalloc(&ctx.d_fused_infer_output, sizeof(NNInferenceOutput)) !=
          cudaSuccess ||
      cudaMalloc(&ctx.d_fused_top_actions, 32 * sizeof(int)) != cudaSuccess ||
      cudaMalloc(&ctx.d_fused_costs, 32 * sizeof(float)) != cudaSuccess) {
    printf("Could not allocate CompContext buffers\n");
    cudaFree(d_data);
    return 1;
  }

  std::vector<NNDebugPerConfig> cfg(32);
  int chosen = -1;
  const int rc = gpucompress::runNNFusedInferenceCtx(
      d_stats, chunk_bytes, error_bound, stream, &ctx, &chosen, nullptr,
      nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr,
      nullptr, nullptr, cfg.data());
  cudaStreamSynchronize(stream);
  if (rc < 0) {
    printf("runNNFusedInferenceCtx failed (%d)\n", rc);
    cudaFree(d_data);
    return 1;
  }

  /* ---- 5. Rank by upstream's own cost ----------------------------------- */
  /* upstream returns cost per config directly; rank is derived here purely for
     display, and does NOT decide the winner -- `chosen` is what its bitonic
     network returned, ties included. */
  std::vector<int> by_cost(32);
  std::iota(by_cost.begin(), by_cost.end(), 0);
  std::stable_sort(by_cost.begin(), by_cost.end(), [&](int a, int b) {
    return cfg[a].cost < cfg[b].cost;
  });
  std::vector<int> rank_of(32, -1);
  for (int r = 0; r < 32; ++r) rank_of[by_cost[r]] = r;

  printf("all 32 candidates, in action order (action = algo + 8*q + 16*sh):\n");
  printf("                          |------ ranking heads ------|"
         "-------- data-quality heads --------|\n");
  printf("act algo      q sh |  ratio   ct_ms   dt_ms  psnr_dB |"
         "     rmse   max_err      mae   ssim |     cost rank\n");
  printf("--------------------------------------------------------"
         "-------------------------------------------------\n");
  for (int a = 0; a < 32; ++a) {
    const int algo = a % 8;
    const int quant = (a / 8) % 2;
    const int shuf = (a / 16) % 2;
    printf("%3d %-9s %d  %d |%7.2f %7.2f %7.2f %8.2f |%9.3g %9.3g %8.3g %6.3f "
           "|%9.4f %4d\n",
           a, kAlgoName[algo], quant, shuf, cfg[a].ratio, cfg[a].comp_time,
           cfg[a].decomp_time, cfg[a].psnr, cfg[a].rmse, cfg[a].max_error,
           cfg[a].mae, cfg[a].ssim, cfg[a].cost, rank_of[a] + 1);
  }

  const int wa = chosen;
  printf("\nselected: action %d -- %s, quantize=%s, shuffle=%s\n", wa,
         kAlgoName[wa % 8], ((wa / 8) % 2) ? "yes" : "no",
         ((wa / 16) % 2) ? "yes" : "no");
  printf("          predicted ratio %.2fx, compress %.2f ms, "
         "decompress %.2f ms, cost %.4f\n",
         cfg[wa].ratio, cfg[wa].comp_time, cfg[wa].decomp_time, cfg[wa].cost);

  printf("\ntop 5 by cost (lower is better):\n");
  for (int r = 0; r < 5; ++r) {
    const int a = by_cost[r];
    printf("  %d. action %2d  %-9s q=%d sh=%d  cost %.4f  ratio %.2fx\n", r + 1,
           a, kAlgoName[a % 8], (a / 8) % 2, (a / 16) % 2, cfg[a].cost,
           cfg[a].ratio);
  }

  gpucompress::freeStatsWorkspace();
  cudaFree(d_data);
  cudaFree(d_stats);
  return 0;
}
