/**
 * Auto-generated execution implementation for core ChiMod
 * Implements Container virtual APIs (Run, Del, SaveTask, LoadTask, NewCopy, Aggregate)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "wrp_cae/core/core_runtime.h"
#include "wrp_cae/core/autogen/core_methods.h"
#include <chimaera/chimaera.h>

namespace wrp_cae::core {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,
                   chi::u32 container_id) {
  // Call base class initialization
  chi::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);
}

void Runtime::Run(chi::u32 method, chi::Future<chi::Task>& task_future, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<CreateTask> typed_task = task_future.GetTaskPtr().template Cast<CreateTask>();
      Create(typed_task, rctx);
      break;
    }
    case Method::kDestroy: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<DestroyTask> typed_task = task_future.GetTaskPtr().template Cast<DestroyTask>();
      Destroy(typed_task, rctx);
      break;
    }
    case Method::kParseOmni: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<ParseOmniTask> typed_task = task_future.GetTaskPtr().template Cast<ParseOmniTask>();
      ParseOmni(typed_task, rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Del(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from private memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.template Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyTask>());
      break;
    }
    case Method::kParseOmni: {
      ipc_manager->DelTask(task_ptr.template Cast<ParseOmniTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        chi::Future<chi::Task>& task_future) {
  switch (method) {
    case Method::kCreate: {
      auto* typed_task = static_cast<CreateTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto* typed_task = static_cast<DestroyTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kParseOmni: {
      auto* typed_task = static_cast<ParseOmniTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive, 
                        chi::Future<chi::Task>& task_future) {
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<CreateTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kDestroy: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<DestroyTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kParseOmni: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<ParseOmniTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<ParseOmniTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LocalLoadIn(chi::u32 method, chi::LocalLoadTaskArchive& archive, 
                           chi::Future<chi::Task>& task_future) {
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<CreateTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDestroy: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<DestroyTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kParseOmni: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<ParseOmniTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<ParseOmniTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LocalSaveOut(chi::u32 method, chi::LocalSaveTaskArchive& archive, 
                            chi::Future<chi::Task>& task_future) {
  switch (method) {
    case Method::kCreate: {
      auto* typed_task = static_cast<CreateTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDestroy: {
      auto* typed_task = static_cast<DestroyTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kParseOmni: {
      auto* typed_task = static_cast<ParseOmniTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::NewCopy(chi::u32 method, chi::Future<chi::Task>& orig_future,
                       chi::Future<chi::Task>& dup_future, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return;
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<CreateTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<DestroyTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kParseOmni: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<ParseOmniTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<ParseOmniTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_future.GetTaskPtr());
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr);
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
}

void Runtime::Aggregate(chi::u32 method, chi::Future<chi::Task>& origin_future,
                         chi::Future<chi::Task>& replica_future) {
  switch (method) {
    case Method::kCreate: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<CreateTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<CreateTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kDestroy: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<DestroyTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<DestroyTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kParseOmni: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<ParseOmniTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<ParseOmniTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    default: {
      // For unknown methods, use base Task Aggregate (which also propagates return codes)
      origin_future->Aggregate(replica_future.GetTaskPtr());
      break;
    }
  }
}

} // namespace wrp_cae::core
