/**
 * Auto-generated execution implementation for admin ChiMod
 * Implements Container virtual APIs (Run, Del, SaveTask, LoadTask, NewCopy, Aggregate)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "chimaera/admin/admin_runtime.h"
#include "chimaera/admin/autogen/admin_methods.h"
#include <chimaera/chimaera.h>

namespace chimaera::admin {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,
                   chi::u32 container_id) {
  // Call base class initialization
  chi::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);
}

void Runtime::Run(chi::u32 method, chi::Future<chi::Task>& task_future, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<CreateTask> typed_task = task_future.GetTaskPtr().template Cast<CreateTask>();
      Create(typed_task, rctx);
      break;
    }
    case Method::kDestroy: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<DestroyTask> typed_task = task_future.GetTaskPtr().template Cast<DestroyTask>();
      Destroy(typed_task, rctx);
      break;
    }
    case Method::kGetOrCreatePool: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<admin::GetOrCreatePoolTask<admin::CreateParams>> typed_task = task_future.GetTaskPtr().template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      GetOrCreatePool(typed_task, rctx);
      break;
    }
    case Method::kDestroyPool: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<DestroyPoolTask> typed_task = task_future.GetTaskPtr().template Cast<DestroyPoolTask>();
      DestroyPool(typed_task, rctx);
      break;
    }
    case Method::kStopRuntime: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<StopRuntimeTask> typed_task = task_future.GetTaskPtr().template Cast<StopRuntimeTask>();
      StopRuntime(typed_task, rctx);
      break;
    }
    case Method::kFlush: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<FlushTask> typed_task = task_future.GetTaskPtr().template Cast<FlushTask>();
      Flush(typed_task, rctx);
      break;
    }
    case Method::kSend: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<SendTask> typed_task = task_future.GetTaskPtr().template Cast<SendTask>();
      Send(typed_task, rctx);
      break;
    }
    case Method::kRecv: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<RecvTask> typed_task = task_future.GetTaskPtr().template Cast<RecvTask>();
      Recv(typed_task, rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Del(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from private memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.template Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyTask>());
      break;
    }
    case Method::kGetOrCreatePool: {
      ipc_manager->DelTask(task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>());
      break;
    }
    case Method::kDestroyPool: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyPoolTask>());
      break;
    }
    case Method::kStopRuntime: {
      ipc_manager->DelTask(task_ptr.template Cast<StopRuntimeTask>());
      break;
    }
    case Method::kFlush: {
      ipc_manager->DelTask(task_ptr.template Cast<FlushTask>());
      break;
    }
    case Method::kSend: {
      ipc_manager->DelTask(task_ptr.template Cast<SendTask>());
      break;
    }
    case Method::kRecv: {
      ipc_manager->DelTask(task_ptr.template Cast<RecvTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        chi::Future<chi::Task>& task_future) {
  switch (method) {
    case Method::kCreate: {
      auto* typed_task = static_cast<CreateTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto* typed_task = static_cast<DestroyTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kGetOrCreatePool: {
      auto* typed_task = static_cast<admin::GetOrCreatePoolTask<admin::CreateParams>*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kDestroyPool: {
      auto* typed_task = static_cast<DestroyPoolTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kStopRuntime: {
      auto* typed_task = static_cast<StopRuntimeTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kFlush: {
      auto* typed_task = static_cast<FlushTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kSend: {
      auto* typed_task = static_cast<SendTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kRecv: {
      auto* typed_task = static_cast<RecvTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive, 
                        chi::Future<chi::Task>& task_future) {
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<CreateTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kDestroy: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<DestroyTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kGetOrCreatePool: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<admin::GetOrCreatePoolTask<admin::CreateParams>>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<admin::GetOrCreatePoolTask<admin::CreateParams>*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kDestroyPool: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<DestroyPoolTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<DestroyPoolTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kStopRuntime: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<StopRuntimeTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<StopRuntimeTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kFlush: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<FlushTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<FlushTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kSend: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<SendTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<SendTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kRecv: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<RecvTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<RecvTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LocalLoadIn(chi::u32 method, chi::LocalLoadTaskArchive& archive, 
                           chi::Future<chi::Task>& task_future) {
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<CreateTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDestroy: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<DestroyTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kGetOrCreatePool: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<admin::GetOrCreatePoolTask<admin::CreateParams>>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<admin::GetOrCreatePoolTask<admin::CreateParams>*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDestroyPool: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<DestroyPoolTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<DestroyPoolTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kStopRuntime: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<StopRuntimeTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<StopRuntimeTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kFlush: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<FlushTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<FlushTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kSend: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<SendTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<SendTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kRecv: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<RecvTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<RecvTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LocalSaveOut(chi::u32 method, chi::LocalSaveTaskArchive& archive, 
                            chi::Future<chi::Task>& task_future) {
  switch (method) {
    case Method::kCreate: {
      auto* typed_task = static_cast<CreateTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDestroy: {
      auto* typed_task = static_cast<DestroyTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kGetOrCreatePool: {
      auto* typed_task = static_cast<admin::GetOrCreatePoolTask<admin::CreateParams>*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDestroyPool: {
      auto* typed_task = static_cast<DestroyPoolTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kStopRuntime: {
      auto* typed_task = static_cast<StopRuntimeTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kFlush: {
      auto* typed_task = static_cast<FlushTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kSend: {
      auto* typed_task = static_cast<SendTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kRecv: {
      auto* typed_task = static_cast<RecvTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::NewCopy(chi::u32 method, chi::Future<chi::Task>& orig_future,
                       chi::Future<chi::Task>& dup_future, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return;
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<CreateTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<DestroyTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kGetOrCreatePool: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kDestroyPool: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<DestroyPoolTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<DestroyPoolTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kStopRuntime: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<StopRuntimeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<StopRuntimeTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kFlush: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<FlushTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<FlushTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kSend: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<SendTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<SendTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kRecv: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<RecvTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<RecvTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_future.GetTaskPtr());
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr);
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
}

void Runtime::Aggregate(chi::u32 method, chi::Future<chi::Task>& origin_future,
                         chi::Future<chi::Task>& replica_future) {
  switch (method) {
    case Method::kCreate: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<CreateTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<CreateTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kDestroy: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<DestroyTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<DestroyTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kGetOrCreatePool: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kDestroyPool: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<DestroyPoolTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<DestroyPoolTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kStopRuntime: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<StopRuntimeTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<StopRuntimeTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kFlush: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<FlushTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<FlushTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kSend: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<SendTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<SendTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kRecv: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<RecvTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<RecvTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    default: {
      // For unknown methods, use base Task Aggregate (which also propagates return codes)
      origin_future->Aggregate(replica_future.GetTaskPtr());
      break;
    }
  }
}

} // namespace chimaera::admin
