#!/usr/bin/env python3
"""Derive a per-kernel register ceiling from a probe build's actual cubin.

Reads `cuobjdump -res-usage <probe binary>` and writes the cap file consumed by
the NVPTXCoroCap pass plugin (-mllvm -clio-coro-cap-file=...).

THE RULE. A kernel that already fits the occupancy budget is not named in the
output at all, so the pass leaves it completely alone and it keeps its natural
allocation. Only kernels measured ABOVE the budget are capped, and the cap is
the budget rounded down to the hardware's register allocation granularity.
That is the whole point of measuring: -maxrregcount clamps every kernel in the
translation unit to one number, and a single constant in the pass clamps every
coroutine kernel to one number. Here each kernel is judged against its own
measurement.

THE BUDGET is an occupancy target, the one genuine policy input:

    budget = regs_per_sm / (ref_threads * target_blocks_per_sm)

Coroutine kernels are latency-bound by construction -- their duty cycle is
waiting on pages, not arithmetic -- so occupancy is the lever that matters and
the default targets 4 blocks/SM at 256 threads (65536/(256*4) = 64 registers).

WHAT THIS CANNOT SEE. Register count is static; the latency/throughput tradeoff
is not. The budget says how much occupancy to buy, and only a runtime
measurement can say whether that was the right purchase for a given kernel.
This tool removes the guesswork about WHICH kernels need a ceiling and what
each one's headroom is; it does not remove the choice of occupancy target.
"""

import argparse
import re
import subprocess
import sys

# Register allocation granularity (registers are handed out in units of 8 on
# every NVIDIA architecture this tree targets). A cap that is not a multiple of
# 8 is silently rounded up by ptxas, which would quietly undo the budget.
REG_GRANULARITY = 8

FUNC_RE = re.compile(r"^\s*Function\s+(\S+):\s*$")
REG_RE = re.compile(r"\bREG:(\d+)\b")
LOCAL_RE = re.compile(r"\bLOCAL:(\d+)\b")


def parse_res_usage(text):
    """-> [(mangled_name, regs, local_bytes)] in declaration order."""
    out = []
    pending = None
    for line in text.splitlines():
        m = FUNC_RE.match(line)
        if m:
            pending = m.group(1)
            continue
        if pending is not None:
            r = REG_RE.search(line)
            if r:
                loc = LOCAL_RE.search(line)
                out.append((pending, int(r.group(1)),
                            int(loc.group(1)) if loc else 0))
                pending = None
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("binary", help="probe build (compiled with the pass off)")
    ap.add_argument("output", help="cap file to write")
    ap.add_argument("--cuobjdump", default="cuobjdump")
    ap.add_argument("--regs-per-sm", type=int, default=65536)
    ap.add_argument("--ref-threads", type=int, default=256)
    ap.add_argument("--target-blocks", type=int, default=4)
    args = ap.parse_args()

    budget = args.regs_per_sm // (args.ref_threads * args.target_blocks)
    budget -= budget % REG_GRANULARITY
    if budget <= 0:
        sys.exit("coro_regcap: occupancy target leaves no register budget")

    try:
        text = subprocess.run([args.cuobjdump, "-res-usage", args.binary],
                              check=True, capture_output=True,
                              text=True).stdout
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        # Degrade to "no ceiling", never to a wrong ceiling.
        sys.stderr.write(f"coro_regcap: probing {args.binary} failed: {e}\n")
        text = ""

    kernels = parse_res_usage(text)
    capped, untouched = [], []
    for name, regs, _local in kernels:
        (capped if regs > budget else untouched).append((name, regs))

    with open(args.output, "w") as f:
        f.write(f"# Generated by tools/coro_regcap/derive_caps.py -- do not edit.\n")
        f.write(f"# probe={args.binary}\n")
        f.write(f"# budget={budget} regs "
                f"({args.regs_per_sm} regs/SM / {args.ref_threads} threads / "
                f"{args.target_blocks} blocks per SM)\n")
        f.write(f"# {len(kernels)} kernels measured, {len(capped)} over budget.\n")
        f.write("# Kernels at or under budget are deliberately absent: the pass\n")
        f.write("# leaves them at their natural allocation.\n")
        for name, regs in capped:
            f.write(f"# measured REG:{regs}\n{name} {budget}\n")

    print(f"coro_regcap: budget {budget} regs; "
          f"{len(capped)} of {len(kernels)} kernels capped, "
          f"{len(untouched)} left at natural allocation")
    if not kernels:
        print("coro_regcap: WARNING no kernels found in the probe binary -- "
              "every coroutine kernel will keep its natural allocation")
    return 0


if __name__ == "__main__":
    sys.exit(main())
