/**
 * Auto-generated execution implementation for compressor ChiMod
 * Implements Container virtual APIs (Run, SaveTask, LoadTask, NewCopyTask, NewTask)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "clio_cte/compressor/compressor_runtime.h"
#include "clio_cte/compressor/autogen/compressor_methods.h"
#include <clio_runtime/clio_runtime.h>
#include <clio_runtime/task.h>  // For TaskResume coroutine return type

namespace clio::cte::compressor {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const clio::run::PoolId &pool_id, const std::string &pool_name,
                   clio::run::u32 container_id) {
  // Call base class initialization
  clio::run::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);

  // Initialize per-method load prediction model
  DefineModel(Method::kMaxMethodId);
  SetMethodNames(Method::GetMethodNames());
}

clio::run::TaskResume Runtime::Run(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task> task_ptr) {
  CLIO_TASK_BODY_BEGIN
  switch (method) {
    case Method::kCreate: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      CLIO_CO_AWAIT(Create(typed_task));
      break;
    }
    case Method::kDestroy: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      CLIO_CO_AWAIT(Destroy(typed_task));
      break;
    }
    case Method::kMonitor: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      CLIO_CO_AWAIT(Monitor(typed_task));
      break;
    }
    case Method::kDynamicSchedule: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<DynamicScheduleTask>();
      CLIO_CO_AWAIT(DynamicSchedule(typed_task));
      break;
    }
    case Method::kCompress: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<CompressTask>();
      CLIO_CO_AWAIT(Compress(typed_task));
      break;
    }
    case Method::kDecompress: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<DecompressTask>();
      CLIO_CO_AWAIT(Decompress(typed_task));
      break;
    }
    case Method::kPollNodeLoad: {
      auto& typed_task = task_ptr.template Cast<PollNodeLoadTask>();
      CLIO_CO_AWAIT(PollNodeLoad(typed_task));
      break;
    }
    case Method::kPollConsumers: {
      auto& typed_task = task_ptr.template Cast<PollConsumersTask>();
      CLIO_CO_AWAIT(PollConsumers(typed_task));
      break;
    }
    // MANUAL (not from codegen): transparently compress/decompress RAW core
    // PutBlob/GetBlob (method ids 15/16) that arrive at the compressor entrypoint
    // -- e.g. gpu_vector page evictions/faults submitted from device code.
    case 15: {  // clio::cte::core::kPutBlob
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PutBlobTask>();
      CLIO_CO_AWAIT(CompressPutBlob(typed_task));
      break;
    }
    case 43: {  // clio::cte::core::kPutBlob
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PodPutBlobTask>();
      CLIO_CO_AWAIT(CompressPodPutBlob(typed_task));
      break;
    }
    case 16: {  // clio::cte::core::kGetBlob
      auto& typed_task = task_ptr.template Cast<clio::cte::core::GetBlobTask>();
      CLIO_CO_AWAIT(DecompressGetBlob(typed_task));
      break;
    }
    case 44: {  // clio::cte::core::kGetBlob
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PodGetBlobTask>();
      CLIO_CO_AWAIT(DecompressPodGetBlob(typed_task));
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  CLIO_CO_RETURN;
  CLIO_TASK_BODY_END
}

void Runtime::SaveTask(clio::run::u32 method, clio::run::SaveTaskArchive& archive, 
                        clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      archive << *typed_task;
      break;
    }
    case Method::kDynamicSchedule: {
      auto& typed_task = task_ptr.template Cast<DynamicScheduleTask>();
      archive << *typed_task;
      break;
    }
    case Method::kCompress: {
      auto& typed_task = task_ptr.template Cast<CompressTask>();
      archive << *typed_task;
      break;
    }
    case Method::kDecompress: {
      auto& typed_task = task_ptr.template Cast<DecompressTask>();
      archive << *typed_task;
      break;
    }
    case Method::kPollNodeLoad: {
      auto& typed_task = task_ptr.template Cast<PollNodeLoadTask>();
      archive << *typed_task;
      break;
    }
    case Method::kPollConsumers: {
      auto& typed_task = task_ptr.template Cast<PollConsumersTask>();
      archive << *typed_task;
      break;
    }
    case 15: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PutBlobTask>();
      archive << *typed_task;
      break;
    }
    case 43: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PodPutBlobTask>();
      archive << *typed_task;
      break;
    }
    case 16: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::GetBlobTask>();
      archive << *typed_task;
      break;
    }
    case 44: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PodGetBlobTask>();
      archive << *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(clio::run::u32 method, clio::run::LoadTaskArchive& archive,
                        clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kDynamicSchedule: {
      auto& typed_task = task_ptr.template Cast<DynamicScheduleTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kCompress: {
      auto& typed_task = task_ptr.template Cast<CompressTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kDecompress: {
      auto& typed_task = task_ptr.template Cast<DecompressTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kPollNodeLoad: {
      auto& typed_task = task_ptr.template Cast<PollNodeLoadTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kPollConsumers: {
      auto& typed_task = task_ptr.template Cast<PollConsumersTask>();
      archive >> *typed_task;
      break;
    }
    case 15: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PutBlobTask>();
      archive >> *typed_task;
      break;
    }
    case 43: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PodPutBlobTask>();
      archive >> *typed_task;
      break;
    }
    case 16: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::GetBlobTask>();
      archive >> *typed_task;
      break;
    }
    case 44: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PodGetBlobTask>();
      archive >> *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::AllocLoadTask(clio::run::u32 method, clio::run::LoadTaskArchive& archive) {
  clio::run::shared_ptr<clio::run::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(clio::run::u32 method, clio::run::DefaultLoadArchive& archive,
                            clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kDynamicSchedule: {
      auto& typed_task = task_ptr.template Cast<DynamicScheduleTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kCompress: {
      auto& typed_task = task_ptr.template Cast<CompressTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kDecompress: {
      auto& typed_task = task_ptr.template Cast<DecompressTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kPollNodeLoad: {
      auto& typed_task = task_ptr.template Cast<PollNodeLoadTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kPollConsumers: {
      auto& typed_task = task_ptr.template Cast<PollConsumersTask>();
      archive >> *typed_task;
      break;
    }
    case 15: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PutBlobTask>();
      archive >> *typed_task;
      break;
    }
    case 43: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PodPutBlobTask>();
      archive >> *typed_task;
      break;
    }
    case 16: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::GetBlobTask>();
      archive >> *typed_task;
      break;
    }
    case 44: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PodGetBlobTask>();
      archive >> *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::LocalAllocLoadTask(clio::run::u32 method, clio::run::DefaultLoadArchive& archive) {
  clio::run::shared_ptr<clio::run::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(clio::run::u32 method, clio::run::DefaultSaveArchive& archive, 
                             clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kDynamicSchedule: {
      auto& typed_task = task_ptr.template Cast<DynamicScheduleTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kCompress: {
      auto& typed_task = task_ptr.template Cast<CompressTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kDecompress: {
      auto& typed_task = task_ptr.template Cast<DecompressTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kPollNodeLoad: {
      auto& typed_task = task_ptr.template Cast<PollNodeLoadTask>();
      archive << *typed_task;
      break;
    }
    case Method::kPollConsumers: {
      auto& typed_task = task_ptr.template Cast<PollConsumersTask>();
      archive << *typed_task;
      break;
    }
    case 15: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PutBlobTask>();
      archive << *typed_task;
      break;
    }
    case 43: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PodPutBlobTask>();
      archive << *typed_task;
      break;
    }
    case 16: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::GetBlobTask>();
      archive << *typed_task;
      break;
    }
    case 44: {
      auto& typed_task = task_ptr.template Cast<clio::cte::core::PodGetBlobTask>();
      archive << *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::NewCopyTask(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task>& orig_task_ptr, bool deep) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return clio::run::shared_ptr<clio::run::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<CreateTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<DestroyTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kMonitor: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<MonitorTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<MonitorTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kDynamicSchedule: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DynamicScheduleTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<DynamicScheduleTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<DynamicScheduleTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kCompress: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CompressTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<CompressTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<CompressTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kDecompress: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DecompressTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<DecompressTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<DecompressTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kPollNodeLoad: {
      auto new_task_ptr = ipc_manager->NewTask<PollNodeLoadTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<PollNodeLoadTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<PollNodeLoadTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kPollConsumers: {
      auto new_task_ptr = ipc_manager->NewTask<PollConsumersTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<PollConsumersTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<PollConsumersTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case 15: {
      auto new_task_ptr = ipc_manager->NewTask<clio::cte::core::PutBlobTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<clio::cte::core::PutBlobTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case 43: {
      auto new_task_ptr = ipc_manager->NewTask<clio::cte::core::PodPutBlobTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<clio::cte::core::PodPutBlobTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case 16: {
      auto new_task_ptr = ipc_manager->NewTask<clio::cte::core::GetBlobTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<clio::cte::core::GetBlobTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case 44: {
      auto new_task_ptr = ipc_manager->NewTask<clio::cte::core::PodGetBlobTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<clio::cte::core::PodGetBlobTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<clio::run::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(ctp::ipc::FullPtr<clio::run::Task>(orig_task_ptr.get()));
        return new_task_ptr;
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
  return clio::run::shared_ptr<clio::run::Task>();
}

clio::run::shared_ptr<clio::run::Task> Runtime::NewTask(clio::run::u32 method) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return clio::run::shared_ptr<clio::run::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kDynamicSchedule: {
      auto new_task_ptr = ipc_manager->NewTask<DynamicScheduleTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kCompress: {
      auto new_task_ptr = ipc_manager->NewTask<CompressTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kDecompress: {
      auto new_task_ptr = ipc_manager->NewTask<DecompressTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kPollNodeLoad: {
      auto new_task_ptr = ipc_manager->NewTask<PollNodeLoadTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kPollConsumers: {
      auto new_task_ptr = ipc_manager->NewTask<PollConsumersTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case 15: {
      auto new_task_ptr = ipc_manager->NewTask<clio::cte::core::PutBlobTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case 43: {
      auto new_task_ptr = ipc_manager->NewTask<clio::cte::core::PodPutBlobTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case 16: {
      auto new_task_ptr = ipc_manager->NewTask<clio::cte::core::GetBlobTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case 44: {
      auto new_task_ptr = ipc_manager->NewTask<clio::cte::core::PodGetBlobTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    default: {
      // For unknown methods, return null pointer
      return clio::run::shared_ptr<clio::run::Task>();
    }
  }
}

void Runtime::AggregateOut(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task>& orig_task,
                        const clio::run::shared_ptr<clio::run::Task>& replica_task) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = orig_task.template Cast<CreateTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = orig_task.template Cast<DestroyTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = orig_task.template Cast<MonitorTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kDynamicSchedule: {
      auto& typed_task = orig_task.template Cast<DynamicScheduleTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kCompress: {
      auto& typed_task = orig_task.template Cast<CompressTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kDecompress: {
      auto& typed_task = orig_task.template Cast<DecompressTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kPollNodeLoad: {
      auto& typed_task = orig_task.template Cast<PollNodeLoadTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kPollConsumers: {
      auto& typed_task = orig_task.template Cast<PollConsumersTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case 15: {
      auto typed_task = orig_task.template Cast<clio::cte::core::PutBlobTask>();
      typed_task->AggregateOut(replica_task);
      break;
    }
    case 43: {
      auto typed_task = orig_task.template Cast<clio::cte::core::PodPutBlobTask>();
      typed_task->AggregateOut(replica_task);
      break;
    }
    case 16: {
      auto typed_task = orig_task.template Cast<clio::cte::core::GetBlobTask>();
      typed_task->AggregateOut(replica_task);
      break;
    }
    case 44: {
      auto typed_task = orig_task.template Cast<clio::cte::core::PodGetBlobTask>();
      typed_task->AggregateOut(replica_task);
      break;
    }
    default: {
      orig_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
  }
}


} // namespace clio::cte::compressor
