/**
 * Auto-generated execution implementation for core ChiMod
 * Implements Container virtual APIs (Run, Del, SaveTask, LoadTask, NewCopy, Aggregate)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "wrp_cte/core/core_runtime.h"
#include "wrp_cte/core/autogen/core_methods.h"
#include <chimaera/chimaera.h>

namespace wrp_cte::core {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,
                   chi::u32 container_id) {
  // Call base class initialization
  chi::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);
}

void Runtime::Run(chi::u32 method, chi::Future<chi::Task>& task_future, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<CreateTask> typed_task = task_future.GetTaskPtr().template Cast<CreateTask>();
      Create(typed_task, rctx);
      break;
    }
    case Method::kDestroy: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<DestroyTask> typed_task = task_future.GetTaskPtr().template Cast<DestroyTask>();
      Destroy(typed_task, rctx);
      break;
    }
    case Method::kRegisterTarget: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<RegisterTargetTask> typed_task = task_future.GetTaskPtr().template Cast<RegisterTargetTask>();
      RegisterTarget(typed_task, rctx);
      break;
    }
    case Method::kUnregisterTarget: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<UnregisterTargetTask> typed_task = task_future.GetTaskPtr().template Cast<UnregisterTargetTask>();
      UnregisterTarget(typed_task, rctx);
      break;
    }
    case Method::kListTargets: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<ListTargetsTask> typed_task = task_future.GetTaskPtr().template Cast<ListTargetsTask>();
      ListTargets(typed_task, rctx);
      break;
    }
    case Method::kStatTargets: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<StatTargetsTask> typed_task = task_future.GetTaskPtr().template Cast<StatTargetsTask>();
      StatTargets(typed_task, rctx);
      break;
    }
    case Method::kGetOrCreateTag: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<core::GetOrCreateTagTask<core::CreateParams>> typed_task = task_future.GetTaskPtr().template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      GetOrCreateTag(typed_task, rctx);
      break;
    }
    case Method::kPutBlob: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<PutBlobTask> typed_task = task_future.GetTaskPtr().template Cast<PutBlobTask>();
      PutBlob(typed_task, rctx);
      break;
    }
    case Method::kGetBlob: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<GetBlobTask> typed_task = task_future.GetTaskPtr().template Cast<GetBlobTask>();
      GetBlob(typed_task, rctx);
      break;
    }
    case Method::kReorganizeBlob: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<ReorganizeBlobTask> typed_task = task_future.GetTaskPtr().template Cast<ReorganizeBlobTask>();
      ReorganizeBlob(typed_task, rctx);
      break;
    }
    case Method::kDelBlob: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<DelBlobTask> typed_task = task_future.GetTaskPtr().template Cast<DelBlobTask>();
      DelBlob(typed_task, rctx);
      break;
    }
    case Method::kDelTag: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<DelTagTask> typed_task = task_future.GetTaskPtr().template Cast<DelTagTask>();
      DelTag(typed_task, rctx);
      break;
    }
    case Method::kGetTagSize: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<GetTagSizeTask> typed_task = task_future.GetTaskPtr().template Cast<GetTagSizeTask>();
      GetTagSize(typed_task, rctx);
      break;
    }
    case Method::kPollTelemetryLog: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<PollTelemetryLogTask> typed_task = task_future.GetTaskPtr().template Cast<PollTelemetryLogTask>();
      PollTelemetryLog(typed_task, rctx);
      break;
    }
    case Method::kGetBlobScore: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<GetBlobScoreTask> typed_task = task_future.GetTaskPtr().template Cast<GetBlobScoreTask>();
      GetBlobScore(typed_task, rctx);
      break;
    }
    case Method::kGetBlobSize: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<GetBlobSizeTask> typed_task = task_future.GetTaskPtr().template Cast<GetBlobSizeTask>();
      GetBlobSize(typed_task, rctx);
      break;
    }
    case Method::kGetContainedBlobs: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<GetContainedBlobsTask> typed_task = task_future.GetTaskPtr().template Cast<GetContainedBlobsTask>();
      GetContainedBlobs(typed_task, rctx);
      break;
    }
    case Method::kTagQuery: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<TagQueryTask> typed_task = task_future.GetTaskPtr().template Cast<TagQueryTask>();
      TagQuery(typed_task, rctx);
      break;
    }
    case Method::kBlobQuery: {
      // Extract task FullPtr from Future and cast to specific type
      hipc::FullPtr<BlobQueryTask> typed_task = task_future.GetTaskPtr().template Cast<BlobQueryTask>();
      BlobQuery(typed_task, rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Del(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from private memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.template Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyTask>());
      break;
    }
    case Method::kRegisterTarget: {
      ipc_manager->DelTask(task_ptr.template Cast<RegisterTargetTask>());
      break;
    }
    case Method::kUnregisterTarget: {
      ipc_manager->DelTask(task_ptr.template Cast<UnregisterTargetTask>());
      break;
    }
    case Method::kListTargets: {
      ipc_manager->DelTask(task_ptr.template Cast<ListTargetsTask>());
      break;
    }
    case Method::kStatTargets: {
      ipc_manager->DelTask(task_ptr.template Cast<StatTargetsTask>());
      break;
    }
    case Method::kGetOrCreateTag: {
      ipc_manager->DelTask(task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>());
      break;
    }
    case Method::kPutBlob: {
      ipc_manager->DelTask(task_ptr.template Cast<PutBlobTask>());
      break;
    }
    case Method::kGetBlob: {
      ipc_manager->DelTask(task_ptr.template Cast<GetBlobTask>());
      break;
    }
    case Method::kReorganizeBlob: {
      ipc_manager->DelTask(task_ptr.template Cast<ReorganizeBlobTask>());
      break;
    }
    case Method::kDelBlob: {
      ipc_manager->DelTask(task_ptr.template Cast<DelBlobTask>());
      break;
    }
    case Method::kDelTag: {
      ipc_manager->DelTask(task_ptr.template Cast<DelTagTask>());
      break;
    }
    case Method::kGetTagSize: {
      ipc_manager->DelTask(task_ptr.template Cast<GetTagSizeTask>());
      break;
    }
    case Method::kPollTelemetryLog: {
      ipc_manager->DelTask(task_ptr.template Cast<PollTelemetryLogTask>());
      break;
    }
    case Method::kGetBlobScore: {
      ipc_manager->DelTask(task_ptr.template Cast<GetBlobScoreTask>());
      break;
    }
    case Method::kGetBlobSize: {
      ipc_manager->DelTask(task_ptr.template Cast<GetBlobSizeTask>());
      break;
    }
    case Method::kGetContainedBlobs: {
      ipc_manager->DelTask(task_ptr.template Cast<GetContainedBlobsTask>());
      break;
    }
    case Method::kTagQuery: {
      ipc_manager->DelTask(task_ptr.template Cast<TagQueryTask>());
      break;
    }
    case Method::kBlobQuery: {
      ipc_manager->DelTask(task_ptr.template Cast<BlobQueryTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        chi::Future<chi::Task>& task_future) {
  switch (method) {
    case Method::kCreate: {
      auto* typed_task = static_cast<CreateTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto* typed_task = static_cast<DestroyTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kRegisterTarget: {
      auto* typed_task = static_cast<RegisterTargetTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kUnregisterTarget: {
      auto* typed_task = static_cast<UnregisterTargetTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kListTargets: {
      auto* typed_task = static_cast<ListTargetsTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kStatTargets: {
      auto* typed_task = static_cast<StatTargetsTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto* typed_task = static_cast<core::GetOrCreateTagTask<core::CreateParams>*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kPutBlob: {
      auto* typed_task = static_cast<PutBlobTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kGetBlob: {
      auto* typed_task = static_cast<GetBlobTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kReorganizeBlob: {
      auto* typed_task = static_cast<ReorganizeBlobTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kDelBlob: {
      auto* typed_task = static_cast<DelBlobTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kDelTag: {
      auto* typed_task = static_cast<DelTagTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kGetTagSize: {
      auto* typed_task = static_cast<GetTagSizeTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kPollTelemetryLog: {
      auto* typed_task = static_cast<PollTelemetryLogTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kGetBlobScore: {
      auto* typed_task = static_cast<GetBlobScoreTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kGetBlobSize: {
      auto* typed_task = static_cast<GetBlobSizeTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kGetContainedBlobs: {
      auto* typed_task = static_cast<GetContainedBlobsTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kTagQuery: {
      auto* typed_task = static_cast<TagQueryTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    case Method::kBlobQuery: {
      auto* typed_task = static_cast<BlobQueryTask*>(task_future.get());
      archive << *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive, 
                        chi::Future<chi::Task>& task_future) {
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<CreateTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kDestroy: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<DestroyTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kRegisterTarget: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<RegisterTargetTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<RegisterTargetTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kUnregisterTarget: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<UnregisterTargetTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<UnregisterTargetTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kListTargets: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<ListTargetsTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<ListTargetsTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kStatTargets: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<StatTargetsTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<StatTargetsTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kGetOrCreateTag: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<core::GetOrCreateTagTask<core::CreateParams>>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<core::GetOrCreateTagTask<core::CreateParams>*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kPutBlob: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<PutBlobTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<PutBlobTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kGetBlob: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<GetBlobTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<GetBlobTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kReorganizeBlob: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<ReorganizeBlobTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<ReorganizeBlobTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kDelBlob: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<DelBlobTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<DelBlobTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kDelTag: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<DelTagTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<DelTagTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kGetTagSize: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<GetTagSizeTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<GetTagSizeTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kPollTelemetryLog: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<PollTelemetryLogTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<PollTelemetryLogTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kGetBlobScore: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<GetBlobScoreTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<GetBlobScoreTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kGetBlobSize: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<GetBlobSizeTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<GetBlobSizeTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kGetContainedBlobs: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<GetContainedBlobsTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<GetContainedBlobsTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kTagQuery: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<TagQueryTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<TagQueryTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    case Method::kBlobQuery: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<BlobQueryTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<BlobQueryTask*>(task_future.get());
      archive >> *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LocalLoadIn(chi::u32 method, chi::LocalLoadTaskArchive& archive, 
                           chi::Future<chi::Task>& task_future) {
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<CreateTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDestroy: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<DestroyTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kRegisterTarget: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<RegisterTargetTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<RegisterTargetTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kUnregisterTarget: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<UnregisterTargetTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<UnregisterTargetTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kListTargets: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<ListTargetsTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<ListTargetsTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kStatTargets: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<StatTargetsTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<StatTargetsTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kGetOrCreateTag: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<core::GetOrCreateTagTask<core::CreateParams>>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<core::GetOrCreateTagTask<core::CreateParams>*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kPutBlob: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<PutBlobTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<PutBlobTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kGetBlob: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<GetBlobTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<GetBlobTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kReorganizeBlob: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<ReorganizeBlobTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<ReorganizeBlobTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDelBlob: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<DelBlobTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<DelBlobTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDelTag: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<DelTagTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<DelTagTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kGetTagSize: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<GetTagSizeTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<GetTagSizeTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kPollTelemetryLog: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<PollTelemetryLogTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<PollTelemetryLogTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kGetBlobScore: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<GetBlobScoreTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<GetBlobScoreTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kGetBlobSize: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<GetBlobSizeTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<GetBlobSizeTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kGetContainedBlobs: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<GetContainedBlobsTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<GetContainedBlobsTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kTagQuery: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<TagQueryTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<TagQueryTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kBlobQuery: {
      // Allocate task using typed NewTask if not already allocated
      if (task_future.IsNull()) {
        auto new_task_ptr = ipc_manager->NewTask<BlobQueryTask>();
        task_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      auto* typed_task = static_cast<BlobQueryTask*>(task_future.get());
      // Call BaseSerializeIn and SerializeIn using LocalLoadTaskArchive
      typed_task->BaseSerializeIn(archive);
      typed_task->SerializeIn(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LocalSaveOut(chi::u32 method, chi::LocalSaveTaskArchive& archive, 
                            chi::Future<chi::Task>& task_future) {
  switch (method) {
    case Method::kCreate: {
      auto* typed_task = static_cast<CreateTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDestroy: {
      auto* typed_task = static_cast<DestroyTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kRegisterTarget: {
      auto* typed_task = static_cast<RegisterTargetTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kUnregisterTarget: {
      auto* typed_task = static_cast<UnregisterTargetTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kListTargets: {
      auto* typed_task = static_cast<ListTargetsTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kStatTargets: {
      auto* typed_task = static_cast<StatTargetsTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kGetOrCreateTag: {
      auto* typed_task = static_cast<core::GetOrCreateTagTask<core::CreateParams>*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kPutBlob: {
      auto* typed_task = static_cast<PutBlobTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kGetBlob: {
      auto* typed_task = static_cast<GetBlobTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kReorganizeBlob: {
      auto* typed_task = static_cast<ReorganizeBlobTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDelBlob: {
      auto* typed_task = static_cast<DelBlobTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDelTag: {
      auto* typed_task = static_cast<DelTagTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kGetTagSize: {
      auto* typed_task = static_cast<GetTagSizeTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kPollTelemetryLog: {
      auto* typed_task = static_cast<PollTelemetryLogTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kGetBlobScore: {
      auto* typed_task = static_cast<GetBlobScoreTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kGetBlobSize: {
      auto* typed_task = static_cast<GetBlobSizeTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kGetContainedBlobs: {
      auto* typed_task = static_cast<GetContainedBlobsTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kTagQuery: {
      auto* typed_task = static_cast<TagQueryTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kBlobQuery: {
      auto* typed_task = static_cast<BlobQueryTask*>(task_future.get());
      // Call BaseSerializeOut and SerializeOut using LocalSaveTaskArchive
      typed_task->BaseSerializeOut(archive);
      typed_task->SerializeOut(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::NewCopy(chi::u32 method, chi::Future<chi::Task>& orig_future,
                       chi::Future<chi::Task>& dup_future, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return;
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<CreateTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<DestroyTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kRegisterTarget: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<RegisterTargetTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<RegisterTargetTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kUnregisterTarget: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<UnregisterTargetTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<UnregisterTargetTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kListTargets: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<ListTargetsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<ListTargetsTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kStatTargets: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<StatTargetsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<StatTargetsTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kGetOrCreateTag: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<core::GetOrCreateTagTask<core::CreateParams>>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kPutBlob: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<PutBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<PutBlobTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kGetBlob: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<GetBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<GetBlobTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kReorganizeBlob: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<ReorganizeBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<ReorganizeBlobTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kDelBlob: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<DelBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<DelBlobTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kDelTag: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<DelTagTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<DelTagTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kGetTagSize: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<GetTagSizeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<GetTagSizeTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kPollTelemetryLog: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<PollTelemetryLogTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<PollTelemetryLogTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kGetBlobScore: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<GetBlobScoreTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<GetBlobScoreTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kGetBlobSize: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<GetBlobSizeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<GetBlobSizeTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kGetContainedBlobs: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<GetContainedBlobsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<GetContainedBlobsTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kTagQuery: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<TagQueryTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<TagQueryTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    case Method::kBlobQuery: {
      // Allocate new task using standard new (returns FullPtr with null allocator)
      auto new_task_ptr = ipc_manager->NewTask<BlobQueryTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_future.GetTaskPtr().template Cast<BlobQueryTask>();
        new_task_ptr->Copy(task_typed);
        // Create Future for the new task
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr.template Cast<chi::Task>());
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_future.GetTaskPtr());
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr);
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
}

void Runtime::Aggregate(chi::u32 method, chi::Future<chi::Task>& origin_future,
                         chi::Future<chi::Task>& replica_future) {
  switch (method) {
    case Method::kCreate: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<CreateTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<CreateTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kDestroy: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<DestroyTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<DestroyTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kRegisterTarget: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<RegisterTargetTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<RegisterTargetTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kUnregisterTarget: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<UnregisterTargetTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<UnregisterTargetTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kListTargets: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<ListTargetsTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<ListTargetsTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kStatTargets: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<StatTargetsTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<StatTargetsTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kGetOrCreateTag: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kPutBlob: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<PutBlobTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<PutBlobTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kGetBlob: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<GetBlobTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<GetBlobTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kReorganizeBlob: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<ReorganizeBlobTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<ReorganizeBlobTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kDelBlob: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<DelBlobTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<DelBlobTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kDelTag: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<DelTagTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<DelTagTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kGetTagSize: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<GetTagSizeTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<GetTagSizeTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kPollTelemetryLog: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<PollTelemetryLogTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<PollTelemetryLogTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kGetBlobScore: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<GetBlobScoreTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<GetBlobScoreTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kGetBlobSize: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<GetBlobSizeTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<GetBlobSizeTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kGetContainedBlobs: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<GetContainedBlobsTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<GetContainedBlobsTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kTagQuery: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<TagQueryTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<TagQueryTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    case Method::kBlobQuery: {
      // Get typed tasks for Aggregate call
      auto typed_origin = origin_future.GetTaskPtr().template Cast<BlobQueryTask>();
      auto typed_replica = replica_future.GetTaskPtr().template Cast<BlobQueryTask>();
      // Call Aggregate (uses task-specific Aggregate if available, otherwise base Task::Aggregate)
      typed_origin->Aggregate(typed_replica);
      break;
    }
    default: {
      // For unknown methods, use base Task Aggregate (which also propagates return codes)
      origin_future->Aggregate(replica_future.GetTaskPtr());
      break;
    }
  }
}

} // namespace wrp_cte::core
