/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 * This file is part of IOWarp Core.
 * BSD 3-Clause License. See LICENSE file.
 */

/**
 * NeuroPress GPU -> HDF5 end-to-end run (issue #693).
 *
 * Generates a 1 GiB dataset directly on the GPU, writes it through the Clio
 * HDF5 VOL connector in 4 MiB chunks, and lets NeuroPress pick the
 * compression configuration for every one of the 256 chunks independently.
 * The compressor pool is configured for INFERENCE + ONLINE LEARNING, so each
 * chunk's real measured outcome feeds back into the model (SGD) before the
 * next chunks are scored -- NeuroPress's own "release" VOL mode
 * (H5VLgpucompress.cu:57).
 *
 * Every selection is logged. Set CLIO_NEUROPRESS_SELECTION_LOG to a path and
 * the compressor runtime writes one CSV row per chunk as it is chosen (see
 * LogNeuroPressSelection in compressor_runtime.cc); this driver sets it if
 * the caller has not.
 *
 * It also dumps the generated bytes to CLIO_NEUROPRESS_E2E_DATA so the
 * native NeuroPress replay consumes the EXACT same input rather than
 * regenerating it and hoping the two generators agree bit for bit.
 *
 * Exploration is deliberately left OFF. With it on, a chunk's stored result
 * can be swapped for an alternative after the fact, so the row logged at
 * selection time would no longer describe what was written -- and this run
 * exists to compare selections. Online learning is the part the user-facing
 * "inference-learning" mode means, and that is on.
 *
 * Two translation units, for the reason neuropress_gpu_demo.cc documents:
 * the clio_cte/compressor headers do not compile under nvcc, so the dataset
 * kernel lives in neuropress_e2e_kernel.cu and this stays a host TU.
 *
 * Run with: bin/neuropress_e2e
 */

#include "clio_vol.h"

#include <hdf5.h>
#include <cuda_runtime.h>

#include <clio_runtime/clio_runtime.h>
#include <clio_runtime/bdev/bdev_client.h>
#include <clio_cte/core/core_client.h>
#include <clio_cte/compressor/compressor_client.h>

#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

// Defined in neuropress_e2e_kernel.cu.
void GenerateNeuroPressE2EDataset(float *d_out, unsigned long long num_elems,
                                  unsigned int elems_per_chunk,
                                  unsigned int num_chunks);

namespace {

constexpr size_t kChunkBytes = 4ull * 1024 * 1024;          // 4 MiB
constexpr size_t kDatasetBytes = 1024ull * 1024 * 1024;     // 1 GiB
constexpr size_t kNumElems = kDatasetBytes / sizeof(float);
constexpr size_t kElemsPerChunk = kChunkBytes / sizeof(float);
constexpr size_t kNumChunks = kDatasetBytes / kChunkBytes;  // 256

const std::string kBackendFile = "/tmp/neuropress_e2e_backend.dat";
const std::string kH5File = "/tmp/neuropress_e2e.h5";
const std::string kDefaultDataDump = "/tmp/neuropress_e2e_data.bin";
const std::string kDefaultSelectionLog = "/tmp/neuropress_e2e_clio.csv";

#define CUDA_CHECK(expr)                                                    \
  do {                                                                      \
    cudaError_t _rc = (expr);                                               \
    if (_rc != cudaSuccess) {                                               \
      std::cerr << "CUDA error at " << __FILE__ << ":" << __LINE__ << ": "  \
                << cudaGetErrorString(_rc) << std::endl;                    \
      std::exit(1);                                                         \
    }                                                                       \
  } while (0)

std::string EnvOr(const char *name, const std::string &fallback) {
  const char *v = std::getenv(name);
  return (v && *v) ? std::string(v) : fallback;
}

hid_t SetupVolEnvironment(clio::run::PoolId *compressor_pool_id) {
  setenv("CLIO_VOL_CHUNK_SIZE", std::to_string(kChunkBytes).c_str(), 1);

  if (!clio::run::CLIO_INIT(clio::run::RuntimeMode::kClient, true)) {
    std::cerr << "CLIO_INIT failed" << std::endl;
    std::exit(1);
  }
  if (!clio::cte::core::CLIO_CTE_CLIENT_INIT()) {
    std::cerr << "CLIO_CTE_CLIENT_INIT failed" << std::endl;
    std::exit(1);
  }

  auto *cte_client = CLIO_CTE_CLIENT;
  // Room for the whole dataset plus headroom: a target too small to hold the
  // run fails deep in PutBlob rather than here.
  auto reg_task = cte_client->AsyncRegisterTarget(
      kBackendFile, clio::run::bdev::BdevType::kFile,
      static_cast<clio::run::u64>(3) * 1024 * 1024 * 1024,
      clio::run::PoolQuery::Local(), clio::run::PoolId(810, 0));
  reg_task.Wait();
  if (reg_task->GetReturnCode() != 0) {
    std::cerr << "AsyncRegisterTarget failed: rc="
              << reg_task->GetReturnCode() << std::endl;
    std::exit(1);
  }

  *compressor_pool_id = clio::run::PoolId(811, 1);
  clio::cte::compressor::CompressorConfig compressor_config;
  compressor_config.neuropress_model_path_ = CLIO_CTP_NEUROPRESS_WEIGHTS_DIR;
  // Inference + online learning, NeuroPress's "release" mode. Exploration
  // stays off: see the file comment.
  //
  // CLIO_NEUROPRESS_E2E_LEARNING=0 turns learning off, which is what makes a
  // strict comparison against native possible: with learning on, each
  // chunk's outcome moves the shared weights, so a selection depends on
  // every chunk that updated the model before it -- and the VOL completes
  // chunks concurrently and out of order. Frozen weights make selection a
  // pure function of the chunk's own statistics, so the two sides must agree
  // chunk for chunk or the port is wrong.
  const char *learn_env = std::getenv("CLIO_NEUROPRESS_E2E_LEARNING");
  const bool learning = !(learn_env && std::string(learn_env) == "0");
  compressor_config.neuropress_online_learning_enabled_ = learning;
  compressor_config.neuropress_exploration_enabled_ = false;
  clio::cte::compressor::Client compressor_client;
  auto create_task = compressor_client.AsyncCreateCompressor(
      clio::run::PoolQuery::Local(), "neuropress_e2e_pool",
      *compressor_pool_id, compressor_config);
  create_task.Wait();
  if (create_task->GetReturnCode() != 0) {
    std::cerr << "AsyncCreateCompressor failed: rc="
              << create_task->GetReturnCode() << std::endl;
    std::exit(1);
  }

  hid_t vol_id = H5VL_clio_register();
  if (vol_id < 0) {
    std::cerr << "H5VL_clio_register failed" << std::endl;
    std::exit(1);
  }
  return vol_id;
}

hid_t MakeCompressedFapl(hid_t vol_id, const clio::run::PoolId &pool_id) {
  hid_t fapl = H5Pcreate(H5P_FILE_ACCESS);
  clio_vol_info_t info = {};
  info.under_vol_id = H5VL_NATIVE;
  info.under_vol_info = nullptr;
  info.chunk_size = kChunkBytes;
  info.compressor_pool_major = pool_id.major_;
  info.compressor_pool_minor = pool_id.minor_;
  if (H5Pset_vol(fapl, vol_id, &info) < 0) {
    std::cerr << "H5Pset_vol failed" << std::endl;
    std::exit(1);
  }
  return fapl;
}

}  // namespace

int main() {
  int device_count = 0;
  if (cudaGetDeviceCount(&device_count) != cudaSuccess || device_count == 0) {
    std::cerr << "No CUDA device available." << std::endl;
    return 77;  // ctest SKIP_RETURN_CODE
  }

  const std::string data_dump = EnvOr("CLIO_NEUROPRESS_E2E_DATA",
                                      kDefaultDataDump);
  // Set before the runtime spins up so the compressor runtime's logger picks
  // it up on its first selection.
  if (!std::getenv("CLIO_NEUROPRESS_SELECTION_LOG")) {
    setenv("CLIO_NEUROPRESS_SELECTION_LOG", kDefaultSelectionLog.c_str(), 1);
  }
  const std::string selection_log =
      EnvOr("CLIO_NEUROPRESS_SELECTION_LOG", kDefaultSelectionLog);

  std::cout << "Dataset:      " << kDatasetBytes / (1024 * 1024) << " MiB ("
            << kNumElems << " floats)\n"
            << "Chunk size:   " << kChunkBytes / (1024 * 1024) << " MiB\n"
            << "Chunks:       " << kNumChunks
            << " (each independently selected by NeuroPress)\n"
            << "Mode:         "
            << ((std::getenv("CLIO_NEUROPRESS_E2E_LEARNING") &&
                 std::string(std::getenv("CLIO_NEUROPRESS_E2E_LEARNING")) == "0")
                    ? "inference only (learning off)"
                    : "inference + online learning")
            << " (exploration off)\n"
            << "Selection log: " << selection_log << "\n"
            << "Data dump:    " << data_dump << "\n"
            << std::endl;

  // Generate on the GPU first: the buffer handed to H5Dwrite is a device
  // pointer, so the dataset is produced and consumed without a host round
  // trip, which is the scenario under test.
  float *d_wbuf = nullptr;
  CUDA_CHECK(cudaMalloc(&d_wbuf, kDatasetBytes));
  GenerateNeuroPressE2EDataset(d_wbuf, kNumElems,
                               static_cast<unsigned>(kElemsPerChunk),
                               static_cast<unsigned>(kNumChunks));
  CUDA_CHECK(cudaGetLastError());
  CUDA_CHECK(cudaDeviceSynchronize());
  std::cout << "Generated " << kDatasetBytes / (1024 * 1024)
            << " MiB on-device." << std::endl;

  // Dump the exact bytes for the native replay. Done once, here, so both
  // sides provably compress the same input.
  {
    std::vector<char> host(kDatasetBytes);
    CUDA_CHECK(cudaMemcpy(host.data(), d_wbuf, kDatasetBytes,
                          cudaMemcpyDeviceToHost));
    std::FILE *f = std::fopen(data_dump.c_str(), "wb");
    if (!f) {
      std::cerr << "cannot open " << data_dump << " for writing" << std::endl;
      return 1;
    }
    if (std::fwrite(host.data(), 1, kDatasetBytes, f) != kDatasetBytes) {
      std::cerr << "short write to " << data_dump << std::endl;
      std::fclose(f);
      return 1;
    }
    std::fclose(f);
    std::cout << "Wrote input bytes to " << data_dump << std::endl;
  }

  clio::run::PoolId compressor_pool_id;
  hid_t vol_id = SetupVolEnvironment(&compressor_pool_id);
  hid_t fapl = MakeCompressedFapl(vol_id, compressor_pool_id);

  std::remove(kH5File.c_str());
  hid_t file = H5Fcreate(kH5File.c_str(), H5F_ACC_TRUNC, H5P_DEFAULT, fapl);
  if (file < 0) { std::cerr << "H5Fcreate failed" << std::endl; return 1; }

  hsize_t dims[1] = {kNumElems};
  hid_t space = H5Screate_simple(1, dims, nullptr);
  hid_t dset = H5Dcreate2(file, "neuropress_e2e_data", H5T_NATIVE_FLOAT,
                          space, H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
  if (dset < 0) { std::cerr << "H5Dcreate2 failed" << std::endl; return 1; }

  auto write_start = std::chrono::steady_clock::now();
  if (H5Dwrite(dset, H5T_NATIVE_FLOAT, H5S_ALL, H5S_ALL, H5P_DEFAULT,
               d_wbuf) < 0) {
    std::cerr << "H5Dwrite failed" << std::endl;
    return 1;
  }
  // The VOL queues each chunk's DynamicSchedule and drains on close, so the
  // selections are not all made until these handles are shut.
  if (H5Dclose(dset) < 0 || H5Sclose(space) < 0 || H5Fclose(file) < 0 ||
      H5Pclose(fapl) < 0) {
    std::cerr << "close after write failed" << std::endl;
    return 1;
  }
  auto write_elapsed =
      std::chrono::duration<double>(std::chrono::steady_clock::now() -
                                    write_start)
          .count();
  double write_mb_s = (kDatasetBytes / (1024.0 * 1024.0)) / write_elapsed;
  std::cout << std::fixed << std::setprecision(2)
            << "H5Dwrite + drain (GPU buffer -> NeuroPress selection -> "
               "compress -> store): "
            << write_elapsed * 1000.0 << " ms (" << write_mb_s << " MiB/s)"
            << std::endl;

  // Reopen fresh so the read genuinely decompresses rather than reusing an
  // in-process handle from the write above.
  hid_t fapl2 = MakeCompressedFapl(vol_id, compressor_pool_id);
  hid_t file2 = H5Fopen(kH5File.c_str(), H5F_ACC_RDONLY, fapl2);
  if (file2 < 0) { std::cerr << "H5Fopen failed" << std::endl; return 1; }
  hid_t dset2 = H5Dopen2(file2, "neuropress_e2e_data", H5P_DEFAULT);
  if (dset2 < 0) { std::cerr << "H5Dopen2 failed" << std::endl; return 1; }

  float *d_rbuf = nullptr;
  CUDA_CHECK(cudaMalloc(&d_rbuf, kDatasetBytes));
  auto read_start = std::chrono::steady_clock::now();
  if (H5Dread(dset2, H5T_NATIVE_FLOAT, H5S_ALL, H5S_ALL, H5P_DEFAULT,
              d_rbuf) < 0) {
    std::cerr << "H5Dread failed" << std::endl;
    return 1;
  }
  auto read_elapsed =
      std::chrono::duration<double>(std::chrono::steady_clock::now() -
                                    read_start)
          .count();
  std::cout << "H5Dread  (decompress -> GPU buffer): "
            << read_elapsed * 1000.0 << " ms ("
            << (kDatasetBytes / (1024.0 * 1024.0)) / read_elapsed << " MiB/s)"
            << std::endl;

  // INTEGRITY: byte-by-byte, not element-by-element.
  //
  // This used to compare floats. Float equality is not bit equality -- it
  // calls +0.0 and -0.0 equal and calls NaN unequal to itself -- so a
  // codec that perturbed a sign bit or produced a NaN would have been
  // reported as either a false pass or a false failure. The dataset is
  // lossless (no error bound is set on the pool), so the correct assertion
  // is that the bytes come back identical.
  //
  // Per-chunk hashes are written alongside, so this run's restored data can
  // be compared against native NeuroPress's chunk for chunk rather than
  // each side only being checked against the source separately.
  std::vector<char> wbuf(kDatasetBytes), rbuf(kDatasetBytes);
  CUDA_CHECK(cudaMemcpy(wbuf.data(), d_wbuf, kDatasetBytes,
                        cudaMemcpyDeviceToHost));
  CUDA_CHECK(cudaMemcpy(rbuf.data(), d_rbuf, kDatasetBytes,
                        cudaMemcpyDeviceToHost));

  const size_t mismatches = 
      (std::memcmp(wbuf.data(), rbuf.data(), kDatasetBytes) == 0)
          ? 0
          : [&] {
              size_t bad = 0;
              for (size_t i = 0; i < kDatasetBytes; ++i) {
                if (wbuf[i] != rbuf[i]) ++bad;
              }
              return bad;
            }();

  size_t first_bad = kDatasetBytes;
  if (mismatches) {
    for (size_t i = 0; i < kDatasetBytes; ++i) {
      if (wbuf[i] != rbuf[i]) { first_bad = i; break; }
    }
  }

  auto Fnv = [](const char *p, size_t n) {
    unsigned long long h = 1469598103934665603ull;
    for (size_t i = 0; i < n; ++i) {
      h ^= static_cast<unsigned char>(p[i]);
      h *= 1099511628211ull;
    }
    return h;
  };

  const std::string integrity_path = selection_log + ".integrity";
  if (std::FILE *f = std::fopen(integrity_path.c_str(), "w")) {
    std::fprintf(f, "chunk,source_hash,restored_hash,bytes_differ\n");
    for (size_t c = 0; c < kNumChunks; ++c) {
      const size_t off = c * kChunkBytes;
      unsigned long long sh = Fnv(wbuf.data() + off, kChunkBytes);
      unsigned long long rh = Fnv(rbuf.data() + off, kChunkBytes);
      size_t bad = 0;
      if (sh != rh) {
        for (size_t i = 0; i < kChunkBytes; ++i) {
          if (wbuf[off + i] != rbuf[off + i]) ++bad;
        }
      }
      std::fprintf(f, "%zu,%llu,%llu,%zu\n", c, sh, rh, bad);
    }
    std::fclose(f);
    std::cout << "Per-chunk integrity hashes: " << integrity_path << std::endl;
  }

  std::cout << (mismatches == 0
                    ? "INTEGRITY VERIFIED: restored bytes identical to source."
                    : "INTEGRITY FAILED: restored bytes differ from source.")
            << " (" << mismatches << " / " << kDatasetBytes << " bytes differ";
  if (mismatches) std::cout << ", first at offset " << first_bad;
  std::cout << ")" << std::endl;

  cudaFree(d_wbuf);
  cudaFree(d_rbuf);
  H5Dclose(dset2);
  H5Fclose(file2);
  H5Pclose(fapl2);
  clio::run::CLIO_RUNTIME_FINALIZE();

  std::cout << "\nSelections logged to " << selection_log << std::endl;
  return mismatches == 0 ? 0 : 1;
}
