#!/usr/bin/env python3
"""
Level-by-level driver for a workflow translated by ``dt_translator.py``.

Reads ``placement.json`` in the output directory, then for each DAG level
runs ``levels/L<i>/<node>.sh`` on every node that has work in that level
(``ssh <node> bash <script>``, one thread per node; nodes that resolve to
this host run the script directly). A level starts only after every node
of the previous level finished, so producer and consumer tasks of
consecutive levels really do run on the nodes the placement says.

Environment: the driver writes ``env.sh`` (sourced by every level script)
from its own environment, keeping variables that match ``ENV_PREFIXES``
plus any ``--env KEY=VALUE``. ``LD_PRELOAD`` is removed from the
environment of the local ``ssh`` processes so an interposer configured
for the tasks is not loaded into ssh itself.

Timing: per-level and total wall time are recorded in ``makespan.json``
(milliseconds). Any task failure aborts the run with the log path.
"""
import argparse
import json
import os
import shlex
import socket
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

sys.stdout.reconfigure(line_buffering=True)
sys.stderr.reconfigure(line_buffering=True)

ENV_PREFIXES = ("LD_PRELOAD", "LD_LIBRARY_PATH", "PATH", "CLIO_", "WRP_",
                "HSHM_", "CTP_", "CHI_", "IOWARP_", "WFBENCH_", "DT_",
                "OMP_", "HOME", "USER")
"""Environment variables (exact names or prefixes) copied into env.sh."""

LOCAL_NAMES = {"localhost", "127.0.0.1", "::1"}


def log(msg: str) -> None:
    """Print a timestamped driver message.

    :param msg: Message text.
    """
    print(f"[run_dist][{datetime.now().strftime('%H:%M:%S')}] {msg}")


def is_local_host(node: str) -> bool:
    """Tell whether ``node`` names the machine the driver runs on.

    :param node: Host name from the placement.
    :return: True for localhost aliases and this host's own names.
    """
    if node in LOCAL_NAMES:
        return True
    me = socket.gethostname()
    mine = {me, me.split(".")[0]}
    try:
        mine.add(socket.getfqdn())
    except OSError:
        pass
    return node in mine or node.split(".")[0] in mine


def load_placement(out_dir: Path) -> Dict:
    """Load ``placement.json`` from the output directory.

    :param out_dir: Translator output directory.
    :return: The parsed placement document.
    """
    path = out_dir / "placement.json"
    if not path.is_file():
        raise SystemExit(f"run_dist: {path} not found; run dt_translator first")
    return json.loads(path.read_text())


def levels_from_placement(placement: Dict) -> List[Tuple[int, Dict[str, List[str]]]]:
    """Group tasks by (level, node).

    :param placement: Parsed placement document.
    :return: Sorted list of ``(level, {node: [task names]})``.
    """
    levels: Dict[int, Dict[str, List[str]]] = {}
    for name, info in placement["tasks"].items():
        levels.setdefault(int(info["level"]), {}).setdefault(
            info["node"], []).append(name)
    return sorted(levels.items())


def write_env_file(out_dir: Path, extra: List[str]) -> Path:
    """Write ``env.sh`` with the exported variables the tasks need.

    :param out_dir: Translator output directory.
    :param extra: ``KEY=VALUE`` strings from ``--env``.
    :return: Path of the written file.
    """
    env: Dict[str, str] = {}
    for key, val in os.environ.items():
        if key in ENV_PREFIXES or any(
                key.startswith(p) for p in ENV_PREFIXES if p.endswith("_")):
            env[key] = val
    for item in extra:
        if "=" not in item:
            raise SystemExit(f"run_dist: --env expects KEY=VALUE, got '{item}'")
        key, val = item.split("=", 1)
        env[key] = val
    path = out_dir / "env.sh"
    lines = ["# generated by run_dist.py; sourced by every level script"]
    for key in sorted(env):
        value = env[key]
        if "${" in value or "$(" in value:
            # Keep shell expansion for values such as
            # CLIO_MEMFD_DIR=${HOME}/clio_${HOSTNAME}; they must resolve on
            # the node that sources env.sh, not here.
            escaped = value.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'export {key}="{escaped}"')
        else:
            lines.append(f"export {key}={shlex.quote(value)}")
    path.write_text("\n".join(lines) + "\n")
    return path


def run_node_script(node: str, script: Path, log_path: Path,
                    ssh_cmd: str, force_ssh: bool) -> int:
    """Run one level script on one node and capture its output.

    :param node: Host name.
    :param script: Absolute path of the level script (on a shared FS).
    :param log_path: Where stdout/stderr of the script go.
    :param ssh_cmd: ssh command prefix (split with shlex).
    :param force_ssh: Use ssh even for the local host.
    :return: The script's exit code.
    """
    if is_local_host(node) and not force_ssh:
        argv = ["bash", str(script)]
    else:
        argv = shlex.split(ssh_cmd) + [node, "bash", str(script)]
    env = dict(os.environ)
    env.pop("LD_PRELOAD", None)
    with open(log_path, "wb") as fp:
        proc = subprocess.run(argv, stdout=fp, stderr=subprocess.STDOUT,
                              env=env, stdin=subprocess.DEVNULL)
    return proc.returncode


def run_level(level: int, nodes: Dict[str, List[str]], out_dir: Path,
              ssh_cmd: str, force_ssh: bool) -> Tuple[float, List[str]]:
    """Run every node script of one level in parallel.

    :param level: Level index.
    :param nodes: ``{node: [tasks]}`` for this level.
    :param out_dir: Translator output directory.
    :param ssh_cmd: ssh command prefix.
    :param force_ssh: Use ssh even for the local host.
    :return: ``(wall_ms, failures)`` where failures are
        ``"node (rc=N) log=PATH"`` strings.
    """
    logs = out_dir / "logs"
    logs.mkdir(exist_ok=True)
    t0 = time.perf_counter()
    jobs = {}
    with ThreadPoolExecutor(max_workers=max(1, len(nodes))) as pool:
        for node in sorted(nodes):
            script = out_dir / "levels" / f"L{level}" / f"{node}.sh"
            if not script.is_file():
                raise SystemExit(f"run_dist: missing level script {script}")
            log_path = logs / f"L{level}_{node}.log"
            jobs[node] = (pool.submit(run_node_script, node, script, log_path,
                                      ssh_cmd, force_ssh), log_path)
    failures = []
    for node, (fut, log_path) in jobs.items():
        rc = fut.result()
        if rc != 0:
            failures.append(f"{node} (rc={rc}) log={log_path}")
    return (time.perf_counter() - t0) * 1000.0, failures


def write_makespan(path: Path, record: Dict) -> None:
    """Write the makespan record as JSON.

    :param path: Output path.
    :param record: Document to write.
    """
    path.write_text(json.dumps(record, indent=2) + "\n")



def stage_inputs(out_dir: Path, placement: Dict, ssh_cmd: str,
                 force_ssh: bool) -> float:
    """Create the data directory inside the CTE namespace and copy the
    translator's staged input files into it, through the interposer.

    Only runs when the placement was generated with the ``clio::`` prefix:
    the tasks then read ``<out>/clio::data/<file>``, which the adapter maps
    to ``<out>/data/<file>`` in the CTE namespace, where nothing exists yet.
    The copy uses ``dd`` (plain read/write syscalls, which the interposer
    sees) on the first node; the time is reported separately from the
    workflow makespan.

    :param out_dir: Translator output directory.
    :param placement: Parsed placement document.
    :param ssh_cmd: ssh command prefix.
    :param force_ssh: Use ssh even for the local host.
    :return: Staging wall time in ms, 0 when no staging is needed, or -1
        when the staging script failed.
    """
    if placement.get("path_prefix") != "clio::":
        return 0.0
    data_dir = out_dir / "data"
    inputs = sorted(f.name for f in data_dir.iterdir() if f.is_file()) \
        if data_dir.is_dir() else []
    script = out_dir / "levels" / "stage.sh"
    script.parent.mkdir(parents=True, exist_ok=True)
    # The adapter strips the "clio::" component and uses the remaining
    # ABSOLUTE path inside the CTE namespace, whose parents do not exist
    # there. Create them one by one with the marker at the root
    # ("/clio::mnt/common/..." -> CTE "/mnt/common/..."); EEXIST is fine.
    lines = ["#!/bin/bash", "set -u", f'cd "{out_dir}" || exit 1',
             f'if [ -f "{out_dir}/env.sh" ]; then . "{out_dir}/env.sh"; fi']
    parts = [p for p in str(out_dir).split("/") if p]
    cte_data = f'/clio::{"/".join(parts)}/data'
    # Python's os.mkdir reaches the interposer through mkdir(2) (coreutils
    # may use mkdirat); print every outcome so a failed run is diagnosable.
    mk = out_dir / "levels" / "stage_mkdir.py"
    dirs = [f'/clio::{"/".join(parts[:d])}' for d in range(1, len(parts) + 1)]
    dirs.append(cte_data)
    mk.write_text("import os, errno\n"
                  f"for d in {dirs!r}:\n"
                  "    try:\n"
                  "        os.mkdir(d, 0o755); print('mkdir ok', d, flush=True)\n"
                  "    except OSError as e:\n"
                  "        print('mkdir', errno.errorcode.get(e.errno, e.errno), d, flush=True)\n")
    lines.append(f'python3 "{mk}"')
    if os.environ.get("DT_STAGE_PROBE"):
        probe = (
            "import os, errno, time, sys\n"
            f"out='{out_dir}'\n"
            "def mk(d):\n"
            "    try: os.mkdir(d, 0o755); return 'ok'\n"
            "    except OSError as e: return errno.errorcode.get(e.errno, e.errno)\n"
            "def st(p):\n"
            "    try: s=os.stat(p); return f'ok size={s.st_size}'\n"
            "    except OSError as e: return errno.errorcode.get(e.errno, e.errno)\n"
            "def cr(p, tries=5):\n"
            "    for i in range(tries):\n"
            "        try:\n"
            "            fd=os.open(p, os.O_CREAT|os.O_WRONLY|os.O_TRUNC, 0o644); os.write(fd, b'y'*4096); os.close(fd); return f'ok after {i} retries'\n"
            "        except OSError as e:\n"
            "            err=errno.errorcode.get(e.errno, e.errno); time.sleep(0.5)\n"
            "    return err\n"
            "node=os.uname().nodename\n"
            "print('PROBE', node, 'mkdir /clio::ptmp', mk('/clio::ptmp'), flush=True)\n"
            "print('PROBE', node, 'stat /clio::ptmp', st('/clio::ptmp'), flush=True)\n"
            "print('PROBE', node, 'create /clio::ptmp/a.dat', cr('/clio::ptmp/a.dat'), flush=True)\n"
            "print('PROBE', node, 'create /clio::root_b.dat', cr('/clio::root_b.dat'), flush=True)\n"
            "d='/clio::'+out.lstrip('/')+'/data'\n"
            "print('PROBE', node, 'stat out/data', st(d), flush=True)\n"
            "print('PROBE', node, 'create out/data/c.dat', cr(d+'/c.dat'), flush=True)\n"
            "print('PROBE', node, 'mkdir out/data2', mk('/clio::'+out.lstrip('/')+'/data2'), flush=True)\n"
            "print('PROBE', node, 'create out/data2/d.dat', cr('/clio::'+out.lstrip('/')+'/data2/d.dat'), flush=True)\n"
            "# real NFS dir + CTE dir with the same name\n"
            "try: os.mkdir(out+'/data3')\n"
            "except OSError: pass\n"
            "print('PROBE', node, 'mkdir out/data3 (nfs dir exists)', mk('/clio::'+out.lstrip('/')+'/data3'), flush=True)\n"
            "print('PROBE', node, 'create out/data3/e.dat', cr('/clio::'+out.lstrip('/')+'/data3/e.dat'), flush=True)\n"
            "print('PROBE', node, 'mkdir out/data4 (cte only)', mk('/clio::'+out.lstrip('/')+'/data4'), flush=True)\n"
            "print('PROBE', node, 'create out/data4/f.dat', cr('/clio::'+out.lstrip('/')+'/data4/f.dat'), flush=True)\n"
            "print('PROBE', node, 'create out/data/c2.dat again', cr(d+'/c2.dat'), flush=True)\n")
        probe_path = out_dir / "levels" / "probe.py"
        probe_path.write_text(probe)
        lines.append(f'python3 "{probe_path}"')
        # the same probe from the second node, over ssh, with env.sh sourced
        if len(placement["nodes"]) > 1:
            other = placement["nodes"][1]
            lines.append(f'ssh {other} "cd {out_dir} && . {out_dir}/env.sh && python3 {probe_path}"')
    # Copy with plain open/read/write syscalls: coreutils (dd, cp) go
    # through openat()/copy_file_range(), which the interposer does not see.
    copier = out_dir / "levels" / "stage_copy.py"
    copier.write_text(
        "import os, sys\n"
        "src, dst = sys.argv[1], sys.argv[2]\n"
        "i = os.open(src, os.O_RDONLY)\n"
        "o = os.open(dst, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644)\n"
        "while True:\n"
        "    b = os.read(i, 4 << 20)\n"
        "    if not b: break\n"
        "    v = memoryview(b)\n"
        "    while v:\n"
        "        n = os.write(o, v); v = v[n:]\n"
        "os.close(i); os.close(o)\n")
    run = out_dir.name
    for name in inputs:
        # Flat root-level CTE names, matching dt_translator._path().
        lines.append(f'python3 "{copier}" "data/{name}" "/clio::{run}__{name}" '
                     f'|| exit 3')
    lines.append("exit 0")
    script.write_text("\n".join(lines) + "\n")
    node = placement["nodes"][0]
    log_path = out_dir / "logs" / "stage.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log(f"staging {len(inputs)} input file(s) into the CTE namespace on {node}")
    t0 = time.perf_counter()
    rc = run_node_script(node, script, log_path, ssh_cmd, force_ssh)
    wall_ms = (time.perf_counter() - t0) * 1000.0
    if rc != 0:
        return -1.0
    log(f"staging done in {wall_ms:.1f} ms")
    return wall_ms

def run_workflow(out_dir: Path, ssh_cmd: str, force_ssh: bool,
                 extra_env: List[str], max_level: Optional[int]) -> int:
    """Run all levels and record ``makespan.json``.

    :param out_dir: Translator output directory.
    :param ssh_cmd: ssh command prefix.
    :param force_ssh: Use ssh even for the local host.
    :param extra_env: ``KEY=VALUE`` strings for env.sh.
    :param max_level: Stop after this level (debugging aid), or None.
    :return: Process exit code (0 = all levels succeeded).
    """
    placement = load_placement(out_dir)
    levels = levels_from_placement(placement)
    env_path = write_env_file(out_dir, extra_env)
    log(f"placement: {len(placement['tasks'])} tasks, {len(levels)} levels, "
        f"nodes={placement['nodes']}, env={env_path}")
    record = {"status": "running", "out_dir": str(out_dir),
              "recipe": placement.get("recipe"),
              "placement": placement.get("placement"),
              "nodes": placement["nodes"], "levels": [], "total_ms": None,
              "start": datetime.now(timezone.utc).isoformat()}
    makespan_path = out_dir / "makespan.json"
    stage_ms = stage_inputs(out_dir, placement, ssh_cmd, force_ssh)
    if stage_ms < 0:
        record["status"] = "failed"
        record["failures"] = ["stage_inputs"]
        write_makespan(makespan_path, record)
        print("run_dist: input staging FAILED (see logs/stage.log)",
              file=sys.stderr)
        return 1
    record["stage_ms"] = round(stage_ms, 1)
    t_start = time.perf_counter()
    for level, nodes in levels:
        if max_level is not None and level > max_level:
            break
        n_tasks = sum(len(v) for v in nodes.values())
        log(f"level {level}: {n_tasks} tasks on {sorted(nodes)}")
        wall_ms, failures = run_level(level, nodes, out_dir, ssh_cmd, force_ssh)
        record["levels"].append({"level": level, "nodes": sorted(nodes),
                                 "tasks": n_tasks, "wall_ms": round(wall_ms, 1)})
        log(f"level {level} done in {wall_ms:.1f} ms")
        if failures:
            record["status"] = "failed"
            record["failures"] = failures
            record["total_ms"] = round((time.perf_counter() - t_start) * 1000.0, 1)
            record["end"] = datetime.now(timezone.utc).isoformat()
            write_makespan(makespan_path, record)
            print(f"run_dist: level {level} FAILED on: " + "; ".join(failures),
                  file=sys.stderr)
            return 1
        write_makespan(makespan_path, record)
    record["status"] = "ok"
    record["total_ms"] = round((time.perf_counter() - t_start) * 1000.0, 1)
    record["end"] = datetime.now(timezone.utc).isoformat()
    write_makespan(makespan_path, record)
    log(f"workflow OK: total {record['total_ms']:.1f} ms -> {makespan_path}")
    return 0


def main(argv=None) -> int:
    """CLI entry point.

    :param argv: Argument list (default ``sys.argv[1:]``).
    :return: Process exit code.
    """
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--out", default=str(Path(__file__).resolve().parent),
                   help="translator output directory (default: this file's dir)")
    p.add_argument("--ssh-cmd", default="ssh",
                   help="ssh command prefix, e.g. 'env -u LD_LIBRARY_PATH ssh'")
    p.add_argument("--force-ssh", action="store_true",
                   help="use ssh even for nodes that resolve to this host")
    p.add_argument("--env", action="append", default=[], metavar="KEY=VALUE",
                   help="extra variable exported to every task (repeatable)")
    p.add_argument("--max-level", type=int, default=None,
                   help="stop after this level index (debugging)")
    args = p.parse_args(argv)
    return run_workflow(Path(args.out).resolve(), args.ssh_cmd, args.force_ssh,
                        args.env, args.max_level)


if __name__ == "__main__":
    sys.exit(main())
